### ISSUE TITLE
Error: Backup failed because The dump process failed with exitcode 2 

### ISSUE THREAD

**Issue by ccj9874** [grokability/snipe-it#10176]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I try to generate a backup on this fresh install using docker on Debian. Unfortunately I get faced with a monstrous wall of an error code that I can't seem to determine the cause of. I suspect that its an issue with folder permissions, which seems to be the usual culprit when there is an issue with creating backups. But I'm not sure which folders need permissions or how to give permissions to those folders. I made the backups folder have public access (777) but that didn't seem to fix it.

### Reproduction steps

1. Click Generate backup on web client

### Expected behavior

I expect the backup to be created without error.

### Snipe-IT Version

v5.2.0 build 6339

### Operating System

Debian

### Web Server

Docker

### PHP Version

7.4.3

### Operating System

Windows 10

### Browser

Google Chrome

### Version

94

### Error messages

```shell
Error: Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'snipeit' AND TABLE_NAME = 'accessories';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109) . #0 /var/www/html/vendor/spatie/db-dumper/src/DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 /var/www/html/vendor/spatie/db-dumper/src/Databases/MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(252): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map() #5 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(255): Illuminate\Support\Collection->map() #6 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(169): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(145): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call() #15 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run() #17 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run() #18 /var/www/html/vendor/symfony/console/Application.php(1009): Spatie\Backup\Commands\BaseCommand->run() #19 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand() #20 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun() #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run() #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(185): Illuminate\Console\Application->run() #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(273): Illuminate\Console\Application->call() #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #25 /var/www/html/app/Http/Controllers/SettingsController.php(1072): Illuminate\Support\Facades\Facade::__callStatic() #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\SettingsController->postBackups() #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch() #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController() #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run() #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #32 /var/www/html/app/Http/Middleware/CheckPermissions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckPermissions->handle() #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle() #36 /var/www/html/app/Http/Middleware/AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle() #38 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #40 /var/www/html/app/Http/Middleware/CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle() #42 /var/www/html/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckLocale->handle() #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle() #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then() #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack() #53 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute() #54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute() #55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch() #56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #57 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #59 /var/www/html/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle() #61 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #63 /var/www/html/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle() #65 /var/www/html/app/Http/Middleware/CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle() #67 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle() #69 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #71 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle() #73 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #75 /var/www/html/app/Http/Middleware/NoSessionStore.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\NoSessionStore->handle() #77 /var/www/html/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle() #79 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #80 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then() #81 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #82 /var/www/html/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle() #83 {main} Backup failed because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'snipeit' AND TABLE_NAME = 'accessories';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109) .
```

### Additional context

Is this a fresh install or an upgrade? Fresh install
What OS and web server you're running Snipe-IT on. Debian 11, Snipe-IT v5.2.0 build 6339
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). Docker
Include what you've done so far in the installation, and if you got any error messages along the way. I configured the env, connected to the server from another machine and imported assets via csv.
Indicate whether or not you've manually edited any data directly in the database. I have not.

**Comment by fabricat** [comment]
I have the same issue too, on Snipe-IT v5.3.0 - build 6470 (Docker-compose deployment).

Please, this is **urgent**: we are running without backups in production!

**Comment by kf0mlb** [comment]
@fabricat If it's urgent/production, then you can manually backup the important bits.  I have a cron job that runs a backup nightly for our Docker host in-house.

```
#!/bin/bash

# Export SQL to file
docker exec mysql /usr/bin/mysqldump -u root --password=$(cat 'docker/secrets/mysql-root') phpipam > /home/fbadmin/docker/mysql/bak/phpipam.sql
docker exec mysql /usr/bin/mysqldump -u root --password=$(cat 'docker/secrets/mysql-root') snipeit > /home/fbadmin/docker/mysql/bak/snipeit.sql

# Tar Docker folder with Exclusions
tar czf backup_docker_$(date '+%F').tar.gz \
  --exclude "mysql/db" \
  /home/fbadmin/docker \
  /home/fbadmin/fuse_connection.cfg \
  /home/fbadmin/dockerBackup.sh \
  /home/fbadmin/NOTES

# Mount Azure Blob, mv backup file, unmount Blob
blobfuse /home/fbadmin/blobcontainer \
  --tmp-path=/mnt/ramdisk/blobfusetemp \
  --config-file=/home/fbadmin/fuse_connection.cfg \
  -o attr_timeout=240 -o entry_timeout=240 \
  -o negative_timeout=120

mv /home/fbadmin/backup_docker_$(date '+%F').tar.gz /home/fbadmin/blobcontainer/

umount /home/fbadmin/blobcontainer
rm -rf /home/fbadmin/docker/mysql/bak/*.sql
```

And the Snipe-IT uploads are in my compose file volume mount, which is a subfolder of ~/docker/.

**Comment by fabricat** [comment]
Thank you @firedrow 
Today I took some time to adjust the workaround for my deployment (leveraging `docker-compose`):

    docker-compose exec mysql bash -c '/usr/bin/mysqldump -u root --password=${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE}' | gzip > ${BACKUP_DIR}/${TIMESTAMP}-mysql.gz
    docker run -t --rm --volumes-from $(docker-compose ps -q snipeit) -v ${BACKUP_DIR}:/backup ubuntu tar czf /backup/${TIMESTAMP}-media.tgz --directory=/var/lib/snipeit data/

Anyway, I would prefer to use the **straight** way to do backups, rather than struggling to find a workaround 👎

**Comment by fabricat** [comment]
I found the possible cause of the error: see https://github.com/laravel/framework/issues/34078
Unfortunately, the `snipeit:backup` command does not have a `--column-statistics-off` switch.

Does this mean that Mysql version 5.7 is definitively **incompatible** with the latest Snipe-IT Docker image (which is equipped with `mysqldump` version 8.0)? 😢

**Comment by snipe** [comment]
We don't use the artisan schema dumper, we use spatie backup. (I don't think the schema dumper in laravel existed at that time we implemented backups). It doesn't look like the problem is in MySQL, but rather the version of mysqldump.

You can handle this via the conf file tho: https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109

<blockquote><img src="https://cdn.sstatic.net/Sites/serverfault/Img/apple-touch-icon@2.png?v=9b1f48ae296b" width="48" align="right"><div>Server Fault</div><div><strong><a href="https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109">mysqldump throws: Unknown table 'COLUMN_STATISTICS' in information_schema (1109)</a></strong></div><div>Every time I try to make a mysqldump I get the following error:

$&gt; mysqldump --single-transaction --host host -u user -p db &gt; db.sql
mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXT...</div></blockquote>

**Comment by fabricat** [comment]
Thanks for the info @snipe 👍 I was completely unaware of the backup details, but that's ininfluent: the solution is the same 😄 
The following workaround did the trick for me.

1. Create a file `./bindings/mysqldump-no-column-statistics.cnf` within your Docker Compose path, with the following content:
```
[mysqldump]
column-statistics=0
```
2. Add the following line to the Snipe-IT service within your `docker-compose.yaml`:
```
volumes:
  - ./bindings/mysqldump-no-column-statistics.cnf:/etc/mysql/conf.d/mysqldump-no-column-statistics.cnf
```
3. Restart the Snipe-IT service and try to run a manual backup

**Comment by kf0mlb** [comment]
Has https://github.com/snipe/snipe-it/issues/10176#issuecomment-961510001 worked for anyone else?  I applied this to my docker-compose setup today and I'm still getting the error in Snipe-IT when I try to manually backup.

**Comment by ccj9874** [comment]
I just ended up wiping my machine and starting from scratch, learning how to set up the server locally using MySQL. Took a lot more work but I finally got it done, thankfully the instance I encountered this issue on was just for testing.

**Comment by stepanov1975** [comment]
Hi. Same problem here. I have the latest docker version of snipe-it installed.
When running backup getting:

```
Error: Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'snipeit' AND TABLE_NAME = 'accessories';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109) . #0 /var/www/html/vendor/spatie/db-dumper/src/DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 /var/www/html/vendor/spatie/db-dumper/src/Databases/MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(252): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map() #5 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(255): Illuminate\Support\Collection->map() #6 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(169): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(145): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call() #15 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run() #17 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run() #18 /var/www/html/vendor/symfony/console/Application.php(1009): Spatie\Backup\Commands\BaseCommand->run() #19 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand() #20 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun() #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run() #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(185): Illuminate\Console\Application->run() #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(273): Illuminate\Console\Application->call() #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #25 /var/www/html/app/Http/Controllers/SettingsController.php(1064): Illuminate\Support\Facades\Facade::__callStatic() #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\SettingsController->postBackups() #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch() #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController() #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run() #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #32 /var/www/html/app/Http/Middleware/CheckPermissions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckPermissions->handle() #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle() #36 /var/www/html/app/Http/Middleware/AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle() #38 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #40 /var/www/html/app/Http/Middleware/CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle() #42 /var/www/html/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckLocale->handle() #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle() #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then() #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack() #53 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute() #54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute() #55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch() #56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #57 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #59 /var/www/html/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\PreventBackHistory->handle() #61 /var/www/html/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle() #63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #65 /var/www/html/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle() #67 /var/www/html/app/Http/Middleware/CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle() #69 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle() #71 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #73 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle() #75 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #77 /var/www/html/app/Http/Middleware/NoSessionStore.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\NoSessionStore->handle() #79 /var/www/html/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #80 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle() #81 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #82 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then() #83 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #84 /var/www/html/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle() #85 {main} Backup failed because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'snipeit' AND TABLE_NAME = 'accessories';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109) .
```
I tried workaround from this post https://github.com/snipe/snipe-it/issues/10176#issuecomment-961510001
Still heving the sema problem
docker-compose.yml
```
version: '3'

services:

  snipe-mysql:
    container_name: snipe-mysql
    restart: unless-stopped
    image: mysql:5.6
    env_file:
      - ./.env
    volumes:
      - /docker_installs/snipe_it/database:/var/lib/mysql
      - ./bindings/mysqldump-no-column-statistics.cnf:/etc/mysql/conf.d/mysqldump-no-column-statistics.cnf
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    environment:
      - PUID=1005
      - PGID=1005

  snipe-it:
    restart: unless-stopped
    container_name: snipeit
    image: snipe/snipe-it
    env_file:
      - ./.env
    ports:
      - "8002:80"
    depends_on:
      - snipe-mysql
    volumes:
      - /docker_installs/snipe_it/snipe:/var/lib/snipeit
      - ./bindings/mysqldump-no-column-statistics.cnf:/etc/mysql/conf.d/mysqldump-no-column-statistics.cnf
    environment:
      - PUID=1005
      - PGID=1005

```

**Comment by stefanp2021** [comment]
> Has [#10176 (comment)](https://github.com/snipe/snipe-it/issues/10176#issuecomment-961510001) worked for anyone else? I applied this to my docker-compose setup today and I'm still getting the error in Snipe-IT when I try to manually backup.

Same here! This is not resolved!!!

**Comment by misilot** [comment]
So, I think what is happening is the docker container has a version mysqldump from ```mysql-client``` that is compatible with mysql8, and not mysql 5.7. 

Switching to ```mariadb-client``` in the container allows the backups to function as expected.

Does Snipe-IT support MySQL8, if not it may make sense to switch the package from ```mysql-client``` to ```mariadb-client```.

**Comment by uberbrady** [comment]
I wonder if it's possible for us to include the mysql-no-column-statistics file in the docker container itself? If so, and so long as it doesn't hurt any other versions, that would be my ideal solution. If someone pushed me a PR for that I'd take it.

**Comment by misilot** [comment]
PR coming shortly. Added PR #10509

**Comment by aduzsardi** [comment]
@misilot 's PR won't fix the WebUI backup utility since the webapp doesn't run as root

putting the option in a file like `/etc/mysql/conf.d/column-statistics.cnf` (make sure the file has a **.cnf** extenstion and **no extra dots**) fixes both the WebUI and the CLI backup
```
[mysqldump]
column-statistics = 0
```

**Comment by misilot** [comment]
@aduzsardi sorry, I didn't even think of the web ui. I will fix that.
