### ISSUE TITLE
"People" is empty after restoring backup

### ISSUE THREAD

**Issue by wfillmer** [grokability/snipe-it#10254]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am moving my snipeit instance to a VM. I have a fresh installation of v5.3.0 and everything is working perfectly until I import a backup I made in a working v4.8 environment. 

My assets import just fine and I can see the pictures and information associated with the asset, however the list of "people" is empty. I see the backup. zip has a config folder and the php in the config folder is skipped when restoring:
![rstoreDb](https://user-images.githubusercontent.com/58711337/139508905-4e5c540f-12f1-4cee-8785-3e91b87e8e5f.PNG)

My migration fails with a permissions issue but the permissions have already been set on the folders:
![migrate](https://user-images.githubusercontent.com/58711337/139509163-ac00d6dd-f688-41b0-9793-878f2446d650.PNG)

Permissions: ![permissions](https://user-images.githubusercontent.com/58711337/139509171-e9311b79-c20d-41d3-ad89-63b0b080694c.PNG)

The users that existed before the import are no longer listed. New users can be created but they do not show up in the list of "People". ![newUser](https://user-images.githubusercontent.com/58711337/139509320-589775f7-f406-4267-abc8-ad211112bdef.PNG)

Also, if I try to modify the security settings I will get a 500 | server error  

### Reproduction steps

1. setup new snipeit install (v5.3.0 on Ubuntu 18.04)
2. import backup file from existing database using this cmd: "sudo php artisan snipeit:restore si-backup.sql"

### Expected behavior

Normal restoration of assets and users

### Snipe-IT Version

5.3.0

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.2.24

### Operating System

WIndows

### Browser

Chrome (multiple)

### Error messages

```shell
No error for issue I am having with users. This appears when changing default pwd length requirement:

Illuminate\Database\QueryException thrown with message "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'login_remote_user_header_name' in 'field list' (SQL: update `settings` set `pwd_secure_complexity` = , `pwd_secure_min` = 8, `login_remote_user_custom_logout_url` = ?, `login_remote_user_header_name` = ?, `settings`.`updated_at` = 2021-10-29 17:55:52 where `id` = 1)"

Stacktrace:
#73 Illuminate\Database\QueryException in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
#72 Doctrine\DBAL\Driver\PDO\Exception in /var/www/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
#71 Doctrine\DBAL\Driver\PDO\Exception:new in /var/www/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:87
#70 PDOException in /var/www/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
#69 PDO:prepare in /var/www/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
#68 Doctrine\DBAL\Driver\PDOConnection:prepare in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:484
#67 Illuminate\Database\Connection:Illuminate\Database\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:662
#66 Illuminate\Database\Connection:runQueryCallback in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:629
#65 Illuminate\Database\Connection:run in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:495
#64 Illuminate\Database\Connection:affectingStatement in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:428
#63 Illuminate\Database\Connection:update in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2736
#62 Illuminate\Database\Query\Builder:update in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:799
#61 Illuminate\Database\Eloquent\Builder:update in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:746
#60 Illuminate\Database\Eloquent\Model:performUpdate in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:661
#59 Illuminate\Database\Eloquent\Model:save in /var/www/snipe-it/app/Http/Controllers/SettingsController.php:537
#58 App\Http\Controllers\SettingsController:postSecurity in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#57 Illuminate\Routing\Controller:callAction in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#56 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
#55 Illuminate\Routing\Route:runController in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
#54 Illuminate\Routing\Route:run in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
#53 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
#52 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/CheckPermissions.php:26
#51 App\Http\Middleware\CheckPermissions:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#49 Illuminate\Auth\Middleware\Authenticate:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#48 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/AssetCountForSidebar.php:56
#47 App\Http\Middleware\AssetCountForSidebar:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#46 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php:50
#45 Laravel\Passport\Http\Middleware\CreateFreshApiToken:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/CheckForTwoFactor.php:53
#43 App\Http\Middleware\CheckForTwoFactor:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/CheckLocale.php:37
#41 App\Http\Middleware\CheckLocale:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#40 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#37 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67
#35 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#34 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
#33 Illuminate\Pipeline\Pipeline:then in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:683
#32 Illuminate\Routing\Router:runRouteWithinStack in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
#31 Illuminate\Routing\Router:runRoute in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:624
#30 Illuminate\Routing\Router:dispatchToRoute in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:613
#29 Illuminate\Routing\Router:dispatch in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:170
#28 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:67
#26 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#25 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/PreventBackHistory.php:23
#24 App\Http\Middleware\PreventBackHistory:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#23 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/SecurityHeaders.php:26
#22 App\Http\Middleware\SecurityHeaders:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#21 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#20 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/CheckForDebug.php:25
#18 App\Http\Middleware\CheckForDebug:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/CheckForSetup.php:26
#16 App\Http\Middleware\CheckForSetup:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#15 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/fideloper/proxy/src/TrustProxies.php:57
#14 Fideloper\Proxy\TrustProxies:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#12 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56
#10 Illuminate\Session\Middleware\StartSession:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#9 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63
#8 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/app/Http/Middleware/NoSessionStore.php:27
#6 App\Http\Middleware\NoSessionStore:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/barryvdh/laravel-cors/src/HandlePreflight.php:29
#4 Barryvdh\Cors\HandlePreflight:handle in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
#3 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
#2 Illuminate\Pipeline\Pipeline:then in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:145
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/snipe-it/public/index.php:58
```

**Comment by snipe** [comment]
Did you run migrations? Any time there is a missing column, it's usually because migrations weren't run. (But you should fix that `laravel.log` permissions error as well. It could be that the storage directory is writable, but the `storage/logs` directory isn't, or that the `storage/logs/laravel.log` file isn't.)

**Comment by snipe** [comment]
What I think is happening is that the migrations are failing, but because the log file can't be written to, it's choking there and not giving us the *real* error message. It can't tell us the error because there is an error writing the error. :-/

**Comment by wfillmer** [comment]
You were right about he permissions on the log - weird since permissions on the directory were applied recursively. But I changed them and I am still seeing an error with the migration. This is not supposed to run as sudoer, is it?:
![updatedPermissions](https://user-images.githubusercontent.com/58711337/139510981-71c6d506-42af-4f6f-8c4c-dfd9b6cbaf13.PNG)

**Comment by snipe** [comment]
It's still saying permission denied, so the permissions issue isn't resolved. If you're running this as use `qa`, and it's owned by the `data-www` user+group, it won't be able to write to it.

**Comment by wfillmer** [comment]
This is what I get when running as sudoer
![updatedPermissions_sudoer](https://user-images.githubusercontent.com/58711337/139511146-b1910e17-4bae-469c-9665-33ccebffa591.PNG)
:

**Comment by wfillmer** [comment]
> It's still saying permission denied, so the permissions issue isn't resolved. If you're running this as use `qa`, and it's owned by the `data-www` user+group, it won't be able to write to it.

I thought the snipeit root folder needed to be owned by the web server? Does this mean the migration does need to run as sudoer or root?

Thanks for your help. I am done for the day but will pick this up again tomorrow.

**Comment by snipe** [comment]
You shouldn't need to run anything as root for Snipe-IT, and the directories *do* need to be writable by the web server in order for the app to work properly - but when you're running command-line tools, the user you're logged in as is the user performing the action (in this case, `qa`), which means it needs to be part of that `data-www` group, or you have to su as `data-www`, like `su data-www php artisan snipeit:restore /home/qa/s-restore.zip`.

**Comment by snipe** [comment]
Basically, increase the permissions on the storage directory and subdirs (`chmod -R 777 storage` or ideally whatever is the tightest permissions you can get away with) or add your qa user to the data-www group, OR run the restore command using `su`. You can learn more about that here: https://www.cyberciti.biz/faq/howto-linux-add-user-to-group/

<blockquote><img src="https://www.cyberciti.biz/media/new/faq/2006/03/ubuntu-groups-300x251.jpg" width="48" align="right"><div><img src="https://www.cyberciti.biz/media/new/faq/2018/11/new_icon_amp.png" height="14"> nixCraft</div><div><strong><a href="https://www.cyberciti.biz/faq/howto-linux-add-user-to-group/">Linux Add User To Group Using Command-Line</a></strong></div><div>Describes how to add a user (primary/secondary/new/existing) to a group under Linux using command line options.</div></blockquote>

**Comment by snipe** [comment]
You'll probably want to also run `php artisan db:wipe` first as well, to clear out any tables that were created during the donked migrations. (That will wipe the tables from the database and let you start fresh.)

**Comment by wfillmer** [comment]
That did the trick neatly. Thanks for the help! Not a bug, the problem was with my permissions when restoring the database.
