### ISSUE TITLE
SnipeIT on Kube : Docker Image v6.0.1 - No signature in acceptance agreement after downloading

### ISSUE THREAD

**Issue by haxgad** [grokability/snipe-it#11182]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

SnipeIT on Kube : Docker Image v6.0.1 - No signature when downloading acceptance agreement.

We upgraded from 5.2.0 since it was also broken there, but upgrading did not fix this.

Please help!!!

### Reproduction steps

1. Go to activity reports
2. Go to accepted assets
3. Download acceptance agreement in the history page
4. Missing signature in downloaded document
...

### Expected behavior

Signature should not be missing 

### Screenshots

<img width="411" alt="Screenshot 2022-05-23 at 8 29 26 PM" src="https://user-images.githubusercontent.com/19735097/169819494-3bc19cab-50d4-4a6b-a7ff-0dad456ba1e9.png">

### Snipe-IT Version

6.0.1

### Operating System

Kubernetes

### Web Server

Kubernetes

### PHP Version

7.4.3

### Operating System

MacOS or Windows

### Browser

Chrome

**Comment by snipe** [comment]
This seems like maybe more of a docker config issue than a Snipe-IT issue? Signatures are showing up fine on non-docker setups.

**Comment by donron7** [comment]
Hi Snipe, 

Assets in other parts are working fine - as already reported in another issue, Signatures in general are not available in 6.0.1 as a column to be shown (although they are there in the Storage), and Acceptance PDFs miss header and signature. Things have been working fine up to 5.0.x and only stopped working when upgrading to 6.0/6.0.1

**Comment by ISNWAdmin** [comment]
I'm having the same issue up through 6.0.5 also with a Docker version. Neither the signature image nor the logo image show on the generated PDF.
Images work every where else in Snipe IT, including signatures being viewable in asset history and the logo in various places in SnipeIT. It seems like there may be an issue in how the image locations are referred to when generating the PDF rather than an overall Docker configuration issue - since other parts of SnipeIT can render the signatures without issue.

**Comment by snipe** [comment]
I believe this was already fixed in the Snipe-IT code on master.

**Comment by AnatoleF** [comment]
Latest docker images (v6.0.8 build 8409 latest & develop) still have this issue.

**Comment by uberbrady** [comment]
Hrm. Yeah, it definitely could be something with our storage volume setup in Docker; we have to do some weird stuff there. I'll try and see about getting a fix out.

**Comment by ISNWAdmin** [comment]
I've updated to 6.0.12, but still have broken images on the acceptance PDFs. Setup is Docker. 
Images work everywhere else in SnipeIT - the Docker volumes are referenced correctly. Logo shows on all pages, and signatures show on the asset history page.

Have others using Docker found a way to get the signatures to work?

Here's a new test signature, just taken, showing without issue in the asset history:
![image](https://user-images.githubusercontent.com/66696771/197884719-b3ca1159-04cb-4f45-93ee-90af82981a92.png)

This is what shows in the PDFs instead of logo and signature:
![image](https://user-images.githubusercontent.com/66696771/197885730-d3221380-0942-4676-97f6-365c914b837c.png)

**Comment by snipe** [comment]
Hi there - I know this is a pretty old issue, but I wanted to check and see if you ever got this resolved? If so, can you please close the ticket? If not, can you update us on what version of Snipe-IT you're currently using, so we can see if it's still an issue on latest?

:) Thanks!

**Comment by ISNWAdmin** [comment]
Images are showing up in my Docker instance.

**Comment by snipe** [comment]
Thanks for the update!
