### ISSUE TITLE
PHP exception when loading "List All" assets array (and others) after upgrading to 6.0.4

### ISSUE THREAD

**Issue by RaumfahrerSpiffy** [grokability/snipe-it#11335]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading from v5.4.2 to v6.0.4 certain asset arrays (views) do not load properly and the page displays no results.

If you search for the assets they DO exist, also certain statuses DO work properly, the array just won't populate. The problem seems to affect the "stock" statuses too, not just my custom ones, but there is no pattern. Some custom ones work, some do not; some stock statuses work, some do not.

I do have several custom fields and field sets.

![Screen Shot 2022-06-16 at 13 46 43](https://user-images.githubusercontent.com/56406949/174133886-4a1f9400-2fd5-4e56-b6b2-a4c4418af75f.png)

### Reproduction steps

1. Navigate to "List All"
... Message in exceptions:

Cannot access offset of type string on string
C:\inetpub\wwwroot\snipe-it\app\Http\Transformers\AssetsTransformer.php#120                                                 TypeError

                    `$value = $asset->{$field->convertUnicodeDbSlug()};

                    if (($field->format == 'DATE') && (!is_null($value)) && ($value!='')){
                        $value = Helper::getFormattedDateObject($value)['formatted'];
                    }
                    
                    $fields_array[$field->name] = [`

### Expected behavior

The array and assets should populate as they did in previous versions.

### Screenshots

![Screen Shot 2022-06-16 at 13 46 43](https://user-images.githubusercontent.com/56406949/174134637-f90436dd-70ac-4c6d-a218-aa68465748d6.png)
![Screen Shot 2022-06-16 at 13 59 10](https://user-images.githubusercontent.com/56406949/174135895-8048f1b1-c601-4214-9f40-ed3f516ad8f9.png)
![Screen Shot 2022-06-16 at 13 59 27](https://user-images.githubusercontent.com/56406949/174135909-35fa3697-3450-479d-87ea-a94c2c8c2e51.png)

### Snipe-IT Version

6.0.4

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.7 & 7.4.30

### Error messages

```shell
[2022-06-16 13:43:42] development.ERROR: Cannot access offset of type string on string {"userId":27816,"exception":"[object] (TypeError(code: 0): Cannot access offset of type string on string at C:\\inetpub\\wwwroot\\snipe-it\\app\\Http\\Transformers\\AssetsTransformer.php:120)
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\app\Http\Transformers\AssetsTransformer.php(17): App\Http\Transformers\AssetsTransformer->transformAsset()
#1 C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\Api\AssetsController.php(353): App\Http\Transformers\AssetsTransformer->transformAssets()
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\Api\AssetsController->index()
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Route->run()
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(63): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(723): Illuminate\Pipeline\Pipeline->then()
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRoute()
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch()
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#20 C:\inetpub\wwwroot\snipe-it\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#22 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#24 C:\inetpub\wwwroot\snipe-it\vendor\fruitcake\laravel-cors\src\HandleCors.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#26 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#28 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#30 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#33 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#35 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#37 C:\inetpub\wwwroot\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#39 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#41 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#43 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#44 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#46 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#48 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#50 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#51 C:\inetpub\wwwroot\snipe-it\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#52 {main}


[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]
```

### Additional context

Upgrade from 5.4.2 to 6.0.4

Windows Server 2016

I haven't been able to replicate on the demo, to be honest I'm not sure what to modify. I've tested adding custom status labels and fields but the issue didn't replicate. Guidance would be much appreciated.

I have two servers, (prod and test) both have this issue after upgrading. The prod is still running PHP 7.4.26 which was unchanged in the upgrade process. 

After encountering the issue I thought to test if PHP itself was the problem. I upgraded the test server to PHP 7.4.30 and the error persisted, I upgraded to 8.1.7 and it still persisted.

**Comment by inietov** [comment]
Let me take a closer look at this, this code had been generating a couple of issues since I introduce it some days ago. I didn't anticipate all the cases it could affect.

**Comment by snipe** [comment]
This was fixed yesterday on master. Issue was that we were only looking for not null, so if the db value was blank but not null, it would still try to convert the date.

**Comment by inietov** [comment]
I saw that... but the screenshot posted here have the new condition and still fails:
![image](https://user-images.githubusercontent.com/653557/174143488-8c232869-9350-4433-ba99-1c88f5183c2c.png)

**Comment by snipe** [comment]
@inietov how are you reproducing this failure?

**Comment by inietov** [comment]
I'm not :(
still can't, I think maybe this is caused by some custom date saved as 'tbd' or some not null, not empty value that I can't still get in the system... I'm definitely looking into it, and think it's possible to happen, tho.

**Comment by snipe** [comment]
The change I made last week (earlier this week? wtf is time anymore) should have handled that at the helper method level. 

What I think I'm suggesting here is that if @RaumfahrerSpiffy does a fresh pull, he might have better results, since I only pushed that change out last night.

**Comment by snipe** [comment]
@RaumfahrerSpiffy so the pattern - if I'm right - is that sometimes a field described as a date field in custom fields will have a value of null, and sometimes it has an empty string. Before yesterday's change, the transformer - the thing that takes the data and makes it into a JSON response - was only checking if it was null, not whether or not it actually had a value. Yesterday's fix *should* solve for that scenario, but if it doesn't, there's more work to do. 

@RaumfahrerSpiffy can you confirm whether you see this change in the version you have installed?
https://github.com/snipe/snipe-it/commit/af66f83a3dedbc29f483773dddb3d0112636c81a

**Comment by RaumfahrerSpiffy** [comment]
Let me check with the team for the version, unfortunately I’m out without access at the moment. Sorry for the delay. I’ll have them try a fresh pull as well.

**Comment by uconnyi** [comment]
Thanks @RaumfahrerSpiffy for creating this bug report for us before he left our organization. I'll be taking over and working with @snipe and @inietov. I just tried a fresh pull (php upgrade.php) on our TEST server. Unfortunately we are still having the same issue as before. 

![image](https://user-images.githubusercontent.com/41389646/174615611-84232f0e-22a8-4806-8cd3-5a912e099c00.png)

And I don't see a version/build difference on TEST vs. PROD
![image](https://user-images.githubusercontent.com/41389646/174617409-2613b82c-a0f9-4a20-b2b0-c6afb9e7ae6c.png)

**Comment by inietov** [comment]
I can't reproduce exactly the behavior you are experiencing... But I do can force a different one. I have a fix, so I'm gonna reopen this, append the fix to this issue and wait so it can be merged and you can test it. Let's see if this approach resolves all the observed issues.

**Comment by snipe** [comment]
If you can pull from develop, this PR should hopefully fix the issue. (I can't reproduce your issue locally :( )
https://github.com/snipe/snipe-it/pull/11352

**Comment by uconnyi** [comment]
@snipe pulled from develop on our TEST and the issue is now resolved! Thank you!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
