### ISSUE TITLE
Labels: Assigned to field not showing

### ISSUE THREAD

**Issue by Roman-Frick** [grokability/snipe-it#14328]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When selecting the assigned to field to show on the labels with the new label engine, it is showing in the preview but not the actual label generated for an asset.

### Reproduction steps

1.  Select new label engine
2.  Create a new field and select assigned to as datafield
3. Generate label for an asset which is assigned to someone
...

### Expected behavior

To show all the selected fields on the label

### Snipe-IT Version

v6.3.1 build 12672

### Operating System

Ubuntu (docker)

### Web Server

nginx

### PHP Version

8.1.2-1ubuntu2.14

**Comment by Godmartinz** [comment]
Hi, This issue was addressed recently. Please pull down the latest version.

**Comment by Roman-Frick** [comment]
@Godmartinz Hi, the issue is still existing in v6.3.2 build 12875

**Comment by Roman-Frick** [comment]
Still existing in v6.3.3

**Comment by Roman-Frick** [comment]
It also would be nice if the label was opening in a new tab instead of the current one.
