### ISSUE TITLE
Attempt to read property "fields" on null

### ISSUE THREAD

**Issue by KyryuMaka** [grokability/snipe-it#14531]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Attempt to read property "fields" on null

[10:05:17] LOG.error: ErrorException: Attempt to read property "fields" on null in 
/public_html/app/Http/Controllers/ViewAssetsController.php:43

 // Loop through all the custom fields that are applied to any model the user has assigned
        foreach ($user->assets as $asset) {
            foreach ($asset->model->fieldset->fields as $field) {                                             <======= In Here
                // check and make sure they're allowed to see the value of the custom field
                if ($field->display_in_user_view == '1') {
                    $field_array[$field->db_column] = $field->name;
                }
            }
        }

https://asset.hunghau.org/account/view-assets

### Reproduction steps

1. Click on my account at right top
2. View Assigned Asset
3.
...

### Expected behavior

When i click on my account at right top and then click to View Assigned Asset, it took me 500 error. So i turn debug mode true and check it get me a bug "Attempt to read property "fields" on null"

### Snipe-IT Version

6.0.3 - build 8923

### Operating System

Windows

### Web Server

Cpanel

### PHP Version

8.1.4

**Comment by KyryuMaka** [comment]
Please help me :<<

**Comment by KyryuMaka** [comment]
Anyone help me please ?

**Comment by snipe** [comment]
Pretty sure that was already fixed. Upgrade your Snipe-IT installation.

**Comment by aeroelandt** [comment]
@snipe I am using the docker image snipe/snipe-it:latest and it is still broken for me. Any idea when the docker image is going to get updated?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
