### ISSUE TITLE
[7.0.11]Side navigation not aligned properly

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15385]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

**Cosmetics.**
'Predefined Kits', 'Settings', "Import', 'Requestable Items' use different style from other <li> items, menu icons and text not aligned properly.

### Reproduction steps

Open Snipe-IT

### Expected behavior

'Predefined Kits'
Is: `<i class="fa fa-object-group fa-fw" aria-hidden="true"></i>`
Should be: `<i class="fa`**s**` fa-object-group fa-fw" aria-hidden="true"></i>`

'Import'
Is: `<i class="fas fa-cloud-upload-alt fa-fw fa-fw" aria-hidden="true"></i>`
Should be: `<i class="fas fa-cloud-upload-alt fa-fw" aria-hidden="true"></i>`

'Settings'
Is: `<i class="fa fa-cog" aria-hidden="true"></i>`
Should be: `<i class="fa`**s** `fa-cog `**fa-fw**`" aria-hidden="true"></i>`

'Requestable Items'
Is: `<i class="fa fa-laptop fa-fw" aria-hidden="true"></i>`
Should be: `<i class="fa`**s**` fa-laptop fa-fw" aria-hidden="true"></i>`

### Screenshots

![image](https://github.com/user-attachments/assets/63f0ef70-7f98-4b77-b464-091432bc9cd9)

### Snipe-IT Version

Version v7.0.11 - build 15044 (master)

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.3

### Operating System

Windows 11

### Browser

Edge, Firefox

### Version

Latest

**Comment by snipe** [comment]
This was already fixed in https://github.com/snipe/snipe-it/commit/f6319e11e7103231ffb9c34093560e319c1d0859

**Comment by swift2512** [comment]
I pulled today via girmt (fresh install) and there were these issues with text alignment. In my other instal with older master was an issue with overlapping < on settings cog, but this one is definitely fixrd in fresh install.

**Comment by swift2512** [comment]
@snipe You missed Settings cog. It's still fa fa-cog instead of fa**s** fa-cog
`59                return 'fa fa-cog';`
![image](https://github.com/user-attachments/assets/1f215c68-c4d8-4bcd-a88c-f283363bb9f5)
