### ISSUE TITLE
7.1.14 is reported as 7.0.14

### ISSUE THREAD

**Issue by koelle25** [grokability/snipe-it#15810]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In the footer, the version is reported as 7.0.14. But the tagged release is 7.1.14.
The culprit seems to be here: https://github.com/snipe/snipe-it/commit/a89e17212eacde1a6882ae755b7fec63e1d99a39

### Reproduction steps

1. Update your Snipe-IT instance to 7.1.14
2. Login and look in the footer to see 7.0.14

### Expected behavior

Version is correctly reported as 7.1.14.

### Snipe-IT Version

7.1.14

### Operating System

Official Docker-Image (Ubuntu 22.04.5)

### Web Server

Official Docker-Image (Apache 2.4.52)

### PHP Version

8.1

**Comment by koelle25** [comment]
Ah, I just discovered it's already fixed in master branch:
https://github.com/snipe/snipe-it/commit/647ef6a4b77a9aa08c6a8ed8c0e60252da96bbc2

Should we leave the issue open a bit, for others discovering the same "problem"?

**Comment by QSI-T** [comment]
Hey, I saw the response of @koelle25 but I can report that the Error is still there, I pulled the changes about 5 minutes ago an ran the docker Container and the footer is displaying `Version v7.0.14 - build 15942 (master)` my `git pull` reported:
`Updating 6c85ba349..647ef6a4b`
idk why there is 4b at the end but the other letters match with the commit that @koelle25 is mentioning.

**Comment by koelle25** [comment]
@QSI-T Did you re-build the docker image and restart the container with it after pulling in the changes? Just pulling the changes does not automatically reflect into the docker image.
4b are just the next two characters. The full commit hash is `647ef6a4b77a9aa08c6a8ed8c0e60252da96bbc2`.

**Comment by snipe** [comment]
This is in the release notes, folks.

**Comment by koelle25** [comment]
True, but it seems this info was added later. My notification mail doesn't contain it.

**Comment by snipe** [comment]
It was added 5 minutes after release, yes. Also noted on the blog post and on all of our social media and in Discord. Deleting and reissuing a tag has traditionally caused massive headaches for docker folks, so we tried to keep it simple and just explain why you're seeing it.

I'm sure we'll be releasing again this week, as there's a small issue with the MS Teams integration anyway, so we'll be sure to have the correct version in the footer.

**Comment by koelle25** [comment]
All good, I'm just following Snipe-IT releases directly here in GitHub, not anywhere else, so others probably already have catched this (if they noticed it anyway). I totally understand the decision not re-issuing the tag, I probably wouldn't do it either.

Thank you for the details and explanation, though! You are on top when it comes to communication with your community 😊
