### ISSUE TITLE
Unable to send acceptance reminders

### ISSUE THREAD

**Issue by filipc** [grokability/snipe-it#15874]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When calling `snipeit:acceptance-reminder` command email notifications are not being send

```php

 ErrorException

  Attempt to read property "assignedTo" on null

  at app/Notifications/UnacceptedAssetReminderNotification.php:24
     20▕      */
     21▕     public function __construct($checkout_info, $count)
     22▕     {
     23▕         $this->count = $count;
  ➜  24▕         $this->target = $checkout_info['acceptance']->assignedTo;
     25▕         $this->acceptance = $checkout_info['acceptance'];
     26▕
     27▕     }
     28▕

```

### Reproduction steps

run `php artisan snipeit:acceptance-reminder -vvvv`

### Expected behavior

The emails should be sent.

### Snipe-IT Version

7.0.14

### Operating System

Docker

### Web Server

Nginx

### PHP Version

8.1.2

**Comment by snipe** [comment]
I feel like this may have been fixed already. You might want to upgrade to the latest version.

**Comment by filipc** [comment]
@snipe it is not fixed. I am testing it on 7.1.15 and it is giving me the same error
