### ISSUE TITLE
Search/Sort users issue

### ISSUE THREAD

**Issue by zain3822** [grokability/snipe-it#16141]
Hi,
While exploring "People"/Users as a "SuperUser/Global User" I do see list of users but the search bar is not filtering any data. There is no error etc. just nothing happens. Similarly Sorting is not done, nothing happens. 

Secondly, when I am assigning any accessory to a user, the drop down list has two issues:

Names are being shows as "Last name, First Name, user id (#employee no)", whereas my setting in Admin Panel are "First Name, Last name"
User list is not populated in full. Means while scrolling down, it does give prompt "Loading more results" but the ones already shown becomes visible. Alphabetically Users from A-J are only shown, and then again list shows the already shown Employees.

**I have tried below steps mentioned in Common issues:**

![Image](https://github.com/user-attachments/assets/ee24227a-30f6-44a8-8e68-627ed1ad057a)

![Image](https://github.com/user-attachments/assets/29641f53-5111-4a4c-a6a5-42fa50eabfc4)

**Details of setup are as follows:**

Snipe IT ver: v7.1.16 build 16564 (gfb857ccf5) (Upgraded via Git Pull)
Laravel Ver: 10.48.23
PHP Ver: 8.3.16
Database driver: mysql
Table Storage: localStorage

Issue persisted in 7.1.15 as well. But now my system is upgraded to 7.1.16

**Comment by snipe** [comment]
I haven't been able to reproduce this - are you still seeing this on latest? Also do you have full multipole company support enabled?

**Comment by snipe** [comment]
Any update here? Also is there anything in your logs/browser console?

**Comment by zain3822** [comment]
Hi,
This issue prolonged from v7.1.16 till v8. 0. But after v8.0 this issue was resolved at its own. I didn't change any thing during installation of new versions; issue resolved at it's own. 
Now I am using 8.1.4 and it is working fine.

**Comment by snipe** [comment]
I'm guessing you forgot to run migrations or something. Either way, glad you're sorted.
