### ISSUE TITLE
SnipeIT acceptance reminder mail does not contain the user name anymore after update to v8.0.0

### ISSUE THREAD

**Issue by SebastianKlimczok** [grokability/snipe-it#16371]
After the update to v8.0.0, the acceptance reminder emails sent over the snipeit:acceptance-reminder command do not contain user names any more:
![Image](https://github.com/user-attachments/assets/241f8506-629a-4ac0-8eda-28ddda940c30)

The command also does not show a name, only an empty space, where one would be in previous versions:
![Image](https://github.com/user-attachments/assets/4f5cb6f9-8134-4014-8af8-3383a2b5d118)
The issue persists after updating to v8.0.1 - build 16992

OS:
Ubuntu 22.04.4 LTS

Web Server:
Apache/2.4.57 (Ubuntu)

PHP:
PHP 8.3.14

DB:
MariaDB 10.11.8

**Comment by snipe** [comment]
This was likely fixed in https://github.com/snipe/snipe-it/pull/16361 - if you upgrade to master, you can see if that fixes your issue.

**Comment by SebastianKlimczok** [comment]
After upgrading to v8.0.2 - build 17048 (master), the issue persists, there is still no name shown in the reminder-emails, just an empty spacer after the "Hello".
