### ISSUE TITLE
License Seat Notes are not getting updated when Check-out/Check-in is performed using the REST API

### ISSUE THREAD

**Issue by Flo-R1der** [grokability/snipe-it#16524]
### Description
When performing a License Seat Check-out/Check-in via the **WebUI**, I can enter notes, and these notes are 
- visible on the License Seat via Web UI 
- visible on the License Seat via API
- visible in the Activity-Log via WebUI
- visible in the Activity-Log via API
  
When performing a License Seat Check-out/Check-in via the **REST API** as specified in the [/licenses/:id/seats/:seat_id](https://snipe-it.readme.io/reference/licensesidseatsseat_id-1)-documentation, the note is 
- **not visible on the License Seat via API**
- **not visible on the License Seat via WebUI**
- visible in the Activity-Log via WebUI
- visible in the Activity-Log via API

![Image](https://github.com/user-attachments/assets/6e444939-6958-4359-8203-b47e3d41df10)

As you can see from the screenshot there is also an inconsistency naming of `note`/`notes` when comparing [/licenses/:id/seats/:seat_id](https://snipe-it.readme.io/reference/licensesidseatsseat_id-1) with [/licenses/:id](https://snipe-it.readme.io/reference/licensesid-1).

### Test-Environment:
Servers:
1. Docker-Container snipe/snipe-it:latest; v8.0.4 - build 17196 (master)
2. Windows Server 2019 with IIS Webserver; v7.0.13 - build 15514 (master)

REST API Clients:
1. PostmanRuntime/7.43.2
2. Our own C# application with RestSharp and Json.NET

Also tested on the API-Explorer [/licenses/:id/seats/:seat_id](https://snipe-it.readme.io/reference/licensesidseatsseat_id-1) and it's behaving the same like in the other combinations.

**Comment by Flo-R1der** [comment]
### Reason: `notes` is missing in the LicenseSeat-Model
``````
    protected $fillable = [
        'assigned_to',
        'asset_id',
    ];
``````
see [app/Models/LicenseSeat.php#L30](../blob/master/app/Models/LicenseSeat.php#L30. I also did a quick comparison with the License-Model `$fillable` [app/Models/License.php#L64](../blob/master/app/Models/License.php#L64)

### Possible Solution
Obviously, adding a line with `'notes',` would help. But it comes with an Issue:
- `'notes',` is not described in the [API Reference](https://snipe-it.readme.io/reference/licensesidseatsseat_id-1)
- `'note',` is producing a failure
   - I did not dig into the details, but I think it has to do with the database etc.
   - also, this would be inconsistent compared to the UI, REST PUT [/licenses/:id](https://snipe-it.readme.io/reference/licensesid-1) and all the other areas

-----

### Proposed Changes/Updates
1. In [app/Models/LicenseSeat.php](../blob/master/app/Models/LicenseSeat.php#L30) add the line `'notes',`:
``````
    protected $fillable = [
        'assigned_to',
        'asset_id',
        'notes',
    ];
``````

2. In the [app/Http/Controllers/Api/LicenseSeatsController.php](../blob/master/app/Http/Controllers/Api/LicenseSeatsController.php#L136) replace all 2 occurrences `note` with `notes`

3. Update the [API Reference](https://snipe-it.readme.io/reference/licensesidseatsseat_id-1) with `notes` instead of `note`

<br>

If you like, I can open a PR with these changes, but I think you guys need to update the [API Reference](https://snipe-it.readme.io/reference/licensesidseatsseat_id-1)

**Comment by marcusmoore** [comment]
Thank you for the detailed report and debugging @Flo-R1der 😍 

@Godmartinz's fix should handle this and be merged soon.

**Comment by snipe** [comment]
Thanks for this bug report! This issue has been fixed and merged into the `master` branch, and will be in the next release.

![trek-nods](https://user-images.githubusercontent.com/197404/47946205-b9af5800-dec5-11e8-85af-fce7915a0938.gif)

**Comment by dirkmelzer** [comment]
Hello,

We are currently using version v8.2.1.
Unfortunately, the bug still hasn't been fixed in this version.
I'm unable to update the 'notes' field via the API.
When is the update expected to be available?

Thank you very much for your efforts.

**Comment by snipe** [comment]
Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and be sure to provide the following information:

- Version of Snipe-IT you're running. (If you didn't grab an official release, let us know which branch you pulled from.)
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is displayed in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable [on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `storage/logs/laravel.log` and your webserver's logs.
- Indicate whether or not you've manually edited any data directly in the database
- Indicate that you've read the rest of the [Getting Help documentation](https://snipe-it.readme.io/docs/getting-help) and [Common Issues](https://snipe-it.readme.io/docs/common-issues).

(When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
