### ISSUE TITLE
Default language not applying to users

### ISSUE THREAD

**Issue by Doneven2012** [grokability/snipe-it#16699]
Hi, we've noticed that the default language configured under `settings => localization => Default Language` isn't applying to new users that are created, whether it be from an LDAP sync, web interface or through the API.

We set the default language to French

Tested: 
1. Create a user manually through the SnipeIT GUI
  1.1. Checked the user's profile, the language wasn't set to anything
  1.2. When giving the user an asset, we get an email in English
2. Created a user through the API
  2.1. The language of the user was set to English, US
  2.2. I tried changing the language setup on the API account, didn't change the result
3.  Created a user through a sync with LDAP which runs every 5 minutes
  3.1. The job uses the command: `/var/www/html/snipe-it/artisan snipeit:ldap-sync`
  3.2. It gets created with English, US as its language

I'm not too sure if we're missing a setting or if it's an issue with SnipeIT

**Comment by snipe** [comment]
What do you have set for your `APP_LOCALE` in your env?

**Comment by Doneven2012** [comment]
It was set to en-US, I tried to change it to fr-FR (since France French is normally the most well supported French) and restarted the server (I did a `php artisan config:clear` but wanted to make sure).

I tried to create a user through the API, but same thing happened, the user's language was set to English (US)

**Comment by snipe** [comment]
> If the user has no language set, the language of the notifications sent to users seem to match my own user's language.

That was a bug that was fixed a while back, but we're still only (now) looking at the user's language and fall back to env language instead of assuming the settings -> localization language as we used to. (Notifications have changed a lot over the past year or two.)

**Comment by Doneven2012** [comment]
I understand. I've tried upgrading to the latest version of both snipe-it and PHP (which seems to work at the moment) and making sure my locale was set to fr-FR but I still get the same behavior.

Is there anything I could try if I want to make sure all users gets notifications in a specific language, French in this case? I'm a bit unsure since there are two issues here:
- Users created using the API default to English (US), this doesn't seem to be influenced by the user linked to the API key
- Users created manually don't have a language by default, but receive notifications in the language of the admin account who modified their profile

Worst case we can change every user manually after creating them, but I already have issues with making our team inventory things properly 😅

**Comment by snipe** [comment]
> Users created using the API default to English (US), this doesn't seem to be influenced by the user linked to the API key

You should be able to pass the locale when creating the user via API.

> Users created manually don't have a language by default, but receive notifications in the language of the admin account who modified their profile

I don't think that's true, at least not for the current version.

**Comment by snipe** [comment]
> Worst case we can change every user manually after creating them

If you're manually creating them, you can just pick a locale then, no?

**Comment by Doneven2012** [comment]
> Okay, I think we figured out what was going on. I have a PR up for this: https://github.com/snipe/snipe-it/pull/16709
Perfect! I appreciate it a lot, it'll remove some of the manual work we'd have to do otherwise. Thanks!

Just responding to the rest since I thought I might as well, to give more context, not that it's entirely necessary but I thought I might as well:

> You should be able to pass the locale when creating the user via API.

I might honestly have missed that, I'll look into it! Whether or not the issue is fixed, still a good idea to do that

>> Users created manually don't have a language by default, but receive notifications in the language of the admin account who modified their profile
> 
> I don't think that's true, at least not for the current version.

That's what I tested at that moment on our instance, though my installation (as much as it's been kept up-to-date) is a good 2-3+ years old at this point, so might be related.

> If you're manually creating them, you can just pick a locale then, no?
We create some by API and some are synced through AD, so none are created manually, otherwise it would definitely be the easiest 🙂

**Comment by snipe** [comment]
> though my installation (as much as it's been kept up-to-date) is a good 2-3+ years old at this point, so might be related.

lol yeah - a lot has happened since then.
