### ISSUE TITLE
Can not update Asset Maintenance

### ISSUE THREAD

**Issue by GaoGaoCE** [grokability/snipe-it#17188]
i Read common issue but can not fix this issue . I have 1 maintenance asset and when update complete time , can not. 

<img width="366" alt="Image" src="https://github.com/user-attachments/assets/ba9f1b78-5a04-4ec4-81ec-6ee522f7754a" />

i can create new asset maitenance , delete but can not edit .

**Comment by GaoGaoCE** [comment]
<img width="266" alt="Image" src="https://github.com/user-attachments/assets/e983f0e0-524f-427c-b355-40b6144f8302" />

**Comment by snipe** [comment]
This was already fixed in https://github.com/grokability/snipe-it/pull/17174

**Comment by IT-Rogue523** [comment]
> This was already fixed in [#17174](https://github.com/grokability/snipe-it/pull/17174)

I am on a hosted Version v8.1.15 - build 18405 (master) build, and still having this issue. Is there something that needs to be done for the fix to be applied?

**Comment by snipe** [comment]
@IT-Rogue523 - sure, you can send us an email at support@snipeitapp.com and we'll pull you to the latest on master, which would include this fix. Just be sure to let us know your subdomain. :)
