### ISSUE TITLE
[Bug]: Invalid datetime value on accepted asset email

### ISSUE THREAD

**Issue by Sc00by121** [grokability/snipe-it#18119]
### Snipe-IT Version

v8.3.4 build 20218

### PHP Version

8.3.7

### Composer Version

2.8.10

### MySQL/MariaDB version

MySQL 5.7

### How did you install Snipe-IT?

Git install

### Is this a fresh install or an upgrade?

Upgrade

### What happened?

We are looking at implementing emails on checkin/out however when a user accepts an asset they receive the email but the date/time field with the email contains the following;

`Accepted 29/10/2025 10:50 (Invalid datetime value.)`

There is also NO email sent when an asset it checked IN.  There are no errors in the log and as far as I can tell no attempt from snipe at sending - All other emails are sent OK.  I'm not sure if this is related to this date/time issue. I can create a separate bug report if required

### What browsers are you seeing the problem on?

Microsoft Edge

### Can you reproduce this on the public demo?

N/A

### Do you have full multiple company support enabled?

Yes

### If you have full multiple company support enabled, do you have location scoping to company enabled?

Yes

### Application log output

```shell
Next Carbon\Exceptions\InvalidFormatException: Failed to parse time string (29/10/2025 10:58) at position 0 (2): Unexpected character in F:\WebSites\Snipe-IT\wwwroot\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php:102
Stack trace:
#0 F:\WebSites\Snipe-IT\wwwroot\app\Helpers\Helper.php(1131): Carbon\Carbon->__construct()
#1 F:\WebSites\Snipe-IT\wwwroot\app\Notifications\AcceptanceAssetAcceptedNotification.php(30): App\Helpers\Helper::getFormattedDateObject()
#2 F:\WebSites\Snipe-IT\wwwroot\app\Http\Controllers\Account\AcceptanceController.php(192): App\Notifications\AcceptanceAssetAcceptedNotification->__construct()
#3 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\Account\AcceptanceController->store()
#4 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction()
#5 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(266): Illuminate\Routing\ControllerDispatcher->dispatch()
#6 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(212): Illuminate\Routing\Route->runController()
#7 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(808): Illuminate\Routing\Route->run()
#8 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(170): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 F:\WebSites\Snipe-IT\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#11 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#13 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Session\Middleware\AuthenticateSession->handle()
#15 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Auth\Middleware\Authenticate->handle()
#17 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\AssetCountForSidebar.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\AssetCountForSidebar->handle()
#19 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#21 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForTwoFactor->handle()
#23 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckUserIsActivated->handle()
#25 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckLocale->handle()
#27 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#29 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#31 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#33 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(807): Illuminate\Pipeline\Pipeline->then()
#35 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(786): Illuminate\Routing\Router->runRouteWithinStack()
#36 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(750): Illuminate\Routing\Router->runRoute()
#37 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(739): Illuminate\Routing\Router->dispatchToRoute()
#38 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(201): Illuminate\Routing\Router->dispatch()
#39 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(170): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#40 F:\WebSites\Snipe-IT\wwwroot\vendor\livewire\livewire\src\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle()
#42 F:\WebSites\Snipe-IT\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#44 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Http\Middleware\HandleCors->handle()
#46 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\PreventBackHistory->handle()
#48 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\SecurityHeaders->handle()
#50 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(51): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#52 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#53 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#55 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#56 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForDebug->handle()
#58 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForSetup.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForSetup->handle()
#60 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#62 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#64 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Session\Middleware\StartSession->handle()
#65 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#67 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\NoSessionStore->handle()
#69 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Http\Middleware\TrustProxies->handle()
#71 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Pipeline\Pipeline->then()
#73 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#74 F:\WebSites\Snipe-IT\wwwroot\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#75 {main}
```

### Browser console output

```shell

```

### Common Issues

- [x] I have searched this repo for existing issues related to my issue (including closed issues)
- [x] My APP_URL is set correctly in my .env file (including http or https and no trailing slash)
- [x] I have searched the official Snipe-IT documentation and have checked the Common Issues documentation (where applicable)
- [x] I have run database migrations (where applicable).
- [x] I have attached screenshots and/or videos of the issue (where applicable)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by snipe** [comment]
I just pushed out a fix to master - can you see if that resolves your issue?

**Comment by Sc00by121** [comment]
Sorry for the delay - I've just applied the latest update and the issue is still there with the same error in the log

(Invalid datetime value.)

**Comment by Sc00by121** [comment]
Latest 8.3.7 still has this issue with this in log;

```
[2025-11-26 14:25:17] production.WARNING: DateMalformedStringException: Failed to parse time string (26/11/2025 14:25) at position 0 (2): Unexpected character in F:\WebSites\Snipe-IT\wwwroot\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php:100
Stack trace:
#0 F:\WebSites\Snipe-IT\wwwroot\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php(100): DateTime->__construct()
#1 F:\WebSites\Snipe-IT\wwwroot\app\Helpers\Helper.php(1131): Carbon\Carbon->__construct()
#2 F:\WebSites\Snipe-IT\wwwroot\app\Notifications\AcceptanceItemAcceptedToUserNotification.php(30): App\Helpers\Helper::getFormattedDateObject()
#3 F:\WebSites\Snipe-IT\wwwroot\app\Http\Controllers\Account\AcceptanceController.php(186): App\Notifications\AcceptanceItemAcceptedToUserNotification->__construct()
#4 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\Account\AcceptanceController->store()
#5 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction()
#6 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(266): Illuminate\Routing\ControllerDispatcher->dispatch()
#7 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(212): Illuminate\Routing\Route->runController()
#8 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(808): Illuminate\Routing\Route->run()
#9 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(170): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 F:\WebSites\Snipe-IT\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#12 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#14 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Session\Middleware\AuthenticateSession->handle()
#16 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Auth\Middleware\Authenticate->handle()
#18 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\AssetCountForSidebar.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\AssetCountForSidebar->handle()
#20 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#22 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForTwoFactor->handle()
#24 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckUserIsActivated->handle()
#26 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckLocale->handle()
#28 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#30 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#32 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#34 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(807): Illuminate\Pipeline\Pipeline->then()
#36 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(786): Illuminate\Routing\Router->runRouteWithinStack()
#37 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(750): Illuminate\Routing\Router->runRoute()
#38 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(739): Illuminate\Routing\Router->dispatchToRoute()
#39 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(201): Illuminate\Routing\Router->dispatch()
#40 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(170): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#41 F:\WebSites\Snipe-IT\wwwroot\vendor\livewire\livewire\src\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle()
#43 F:\WebSites\Snipe-IT\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#45 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Http\Middleware\HandleCors->handle()
#47 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\PreventBackHistory->handle()
#49 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\SecurityHeaders->handle()
#51 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(51): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#53 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#54 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#56 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#57 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForDebug->handle()
#59 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForSetup.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForSetup->handle()
#61 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#63 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#65 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Session\Middleware\StartSession->handle()
#66 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#68 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#69 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\NoSessionStore->handle()
#70 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#71 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Http\Middleware\TrustProxies->handle()
#72 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#73 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Pipeline\Pipeline->then()
#74 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#75 F:\WebSites\Snipe-IT\wwwroot\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#76 {main}

Next Carbon\Exceptions\InvalidFormatException: Failed to parse time string (26/11/2025 14:25) at position 0 (2): Unexpected character in F:\WebSites\Snipe-IT\wwwroot\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php:102
Stack trace:
#0 F:\WebSites\Snipe-IT\wwwroot\app\Helpers\Helper.php(1131): Carbon\Carbon->__construct()
#1 F:\WebSites\Snipe-IT\wwwroot\app\Notifications\AcceptanceItemAcceptedToUserNotification.php(30): App\Helpers\Helper::getFormattedDateObject()
#2 F:\WebSites\Snipe-IT\wwwroot\app\Http\Controllers\Account\AcceptanceController.php(186): App\Notifications\AcceptanceItemAcceptedToUserNotification->__construct()
#3 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\Account\AcceptanceController->store()
#4 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction()
#5 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(266): Illuminate\Routing\ControllerDispatcher->dispatch()
#6 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(212): Illuminate\Routing\Route->runController()
#7 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(808): Illuminate\Routing\Route->run()
#8 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(170): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 F:\WebSites\Snipe-IT\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#11 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#13 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Session\Middleware\AuthenticateSession->handle()
#15 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Auth\Middleware\Authenticate->handle()
#17 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\AssetCountForSidebar.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\AssetCountForSidebar->handle()
#19 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#21 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForTwoFactor->handle()
#23 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckUserIsActivated->handle()
#25 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckLocale->handle()
#27 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#29 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#31 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#33 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(807): Illuminate\Pipeline\Pipeline->then()
#35 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(786): Illuminate\Routing\Router->runRouteWithinStack()
#36 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(750): Illuminate\Routing\Router->runRoute()
#37 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(739): Illuminate\Routing\Router->dispatchToRoute()
#38 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(201): Illuminate\Routing\Router->dispatch()
#39 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(170): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#40 F:\WebSites\Snipe-IT\wwwroot\vendor\livewire\livewire\src\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle()
#42 F:\WebSites\Snipe-IT\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#44 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Http\Middleware\HandleCors->handle()
#46 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\PreventBackHistory->handle()
#48 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\SecurityHeaders->handle()
#50 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(51): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#52 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#53 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#55 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#56 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForDebug->handle()
#58 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\CheckForSetup.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\CheckForSetup->handle()
#60 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#62 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#64 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Session\Middleware\StartSession->handle()
#65 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#67 F:\WebSites\Snipe-IT\wwwroot\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): App\Http\Middleware\NoSessionStore->handle()
#69 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(209): Illuminate\Http\Middleware\TrustProxies->handle()
#71 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Pipeline\Pipeline->then()
#73 F:\WebSites\Snipe-IT\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#74 F:\WebSites\Snipe-IT\wwwroot\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#75 {main}   
```

**Comment by Sc00by121** [comment]
Have found that setting the following in .env has fixed the issue

`APP_TIMEZONE='Europe/London'
APP_LOCALE=en-GB`
