### ISSUE TITLE
[v. 5.0.0] Maintenance notes do not store correct encoding/charset with & and "

### ISSUE THREAD

**Issue by roratonet** [grokability/snipe-it#8544]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When writing notes into the asset maintenance (not tested with other fields), using the & (ampersand) and " (double quotes), the app stores &amp and &quot instead;

**To Reproduce**
1. create a new asset maintenance or edit existing
2. include the & and/or " characters in the "notes" field and save
3. visualize the output which is &amp&quot

**Expected behavior**
Characters like & and " should be visualised with & and "

**Screenshots**
No screenshots but tested on official Snipe-IT demo:
https://demo.snipeitapp.com/hardware/maintenances
https://demo.snipeitapp.com/hardware/maintenances/4/edit

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.0
 - OS: Debian 10
 - Web Server: Nginx
 - PHP Version 7.3.19-1~deb10u1

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome
 - Version Latest

**Error Messages**
From Laravel DEBUG mode:
update `asset_maintenances` set `notes` = 'Touchbar &amp On/Off', `asset_maintenances`.`updated_at` = '2020-10-20 15:32:29' where `id` = 21

Bindings | 0. Touchbar & On/Off
1. 2020-10-20 15:32:29
2. 21

**Additional context**
- Is this a fresh install or an upgrade? Upgrade from latest v4
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
On the database it is stored like the SQL statement above

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by roratonet** [comment]
Bug present on v.5.0.3 aswell
https://develop.snipeitapp.com/hardware/1#maintenances

<blockquote><img src="https://develop.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://develop.snipeitapp.com/hardware/1#maintenances">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by jovibroz** [comment]
This was actually one of the first things I noticed after struggling thru the upgrade to v.5.0.0 and I immediately just changed the name.

Looked like this (Swedish language):


2020-10-21 08:43 | Johan Hörnqvist | uppdatering | Monitor NADIA (00161) |   |   | name: 20&quot; Monitor NADIA  Monitor NADIA
-- | -- | -- | -- | -- | -- | --


EDIT: Hm haha here the formatting works and the "20 & quot; " doesn't show

**Comment by snipe** [comment]
This is now fixed on develop

**Comment by roratonet** [comment]
https://user-images.githubusercontent.com/22026195/103459856-2460b600-4d12-11eb-90ce-f4fbc589cde3.mov

Issue is still there :(
