### ISSUE TITLE
V5.0 - Asset-ID wont increase automatically

### ISSUE THREAD

**Issue by GustelDE** [grokability/snipe-it#8555]
Hi,

with V5, if I copy an Asset, the new Asset-ID wont increase to the next free number.
It stays the same number and says, Asset-ID already present, I must enter the next (free) number manually.

Behaviour not with V4.x

![01](https://user-images.githubusercontent.com/26502186/96679856-c0fef300-1374-11eb-9e61-372c8c489098.jpg)
![02](https://user-images.githubusercontent.com/26502186/96680114-3074e280-1375-11eb-85f4-a435298c0033.jpg)
![Unbenannt-1](https://user-images.githubusercontent.com/26502186/96682312-ea218280-1378-11eb-9449-b07f86752966.jpg)

Additional Information:
It works for the first copied Asset, but for all further copies, the number stays the same.
As above: 888 was the next free number, but 889 showed still 888.

**Comment by jovibroz** [comment]
I'm at 303 and duplicate works, 304, 305 no problem here..

Though, I'd like the counter to sense the highest used number. If I delete the test assets 304,305 I just created, next auto-increment number will still be 306. So I have to remember to manually turn back the counter if deleting an asset.

**Comment by GustelDE** [comment]
Hi, im at 887. If I copy an Asset, the new one gets 888. Thats right.
The next copy gets 888 again, and all new copies will get 888. This is reproducible with V5.0.0 and V5.0.1 With V4.9.5 everything worked fine!

The only way the counter goes up ist to:
**docker exec -it snipe-it_snipe-it_1 sh**
And then execute:
**php artisan cache:clear**
Then it works for the next number. The next copied Asset gets 889, but it stuck at 889 again untill I do **php artisan cache:clear** again...

As told, Docker-Compose-Version V5.0.1

**Comment by GustelDE** [comment]
Screenshots:
![01](https://user-images.githubusercontent.com/26502186/96794506-a1141180-13fe-11eb-8e6f-eda9e1a4cb36.jpg)
![02](https://user-images.githubusercontent.com/26502186/96794752-0f58d400-13ff-11eb-914c-b094460f4ef3.jpg)
![03](https://user-images.githubusercontent.com/26502186/96794523-a40f0200-13fe-11eb-8d12-d5d9ef9bd150.jpg)
![04](https://user-images.githubusercontent.com/26502186/96794525-a5402f00-13fe-11eb-9e68-721aa0170d5e.jpg)
![05](https://user-images.githubusercontent.com/26502186/96794529-a6715c00-13fe-11eb-951d-d7e96d014eea.jpg)

And under Settings -> Asset Tags no changes are possible!
Everything triggers an Error!
![06](https://user-images.githubusercontent.com/26502186/96794763-154eb500-13ff-11eb-96ae-95153c2b15da.jpg)

Unfortunately I have to consider V5.0.0 and V5.0.1 as NOT stable!
There is almost everything broken, its a public Beta, but far away from a Stable :/

**Comment by GustelDE** [comment]
Problem **partially** solved by this:
https://github.com/snipe/snipe-it/issues/8578

Only the missing prefix or 000 persist.

**Comment by snipe** [comment]
> Unfortunately I have to consider V5.0.0 and V5.0.1 as NOT stable!
> There is almost everything broken, its a public Beta, but far away from a Stable :/

We have customers already using v5.0.1, so that seems unlikely, but I would like to get to the bottom of this. 

If you turn debug on and enable the debug bar, what does the message bag say when you try to ave the settings?

**Comment by xam-ps** [comment]
I can confirm, the problem with the missing leading zeros. 

![](https://user-images.githubusercontent.com/26502186/96794525-a5402f00-13fe-11eb-9e68-721aa0170d5e.jpg)

That bug is still existing in Version 5.0.9

**Comment by LEOkonami** [comment]
I have the same issue and I think I found the source of this issue...
when I go to Asset Tag Settings I can see the "Next auto-increment" stuck on 595... 

I get this error message and I have an asset with the number and I can't even change the number (Getting:  Error: Please check the form below for errors
)
![image](https://user-images.githubusercontent.com/39458766/102777980-64cb4600-439a-11eb-8530-df7c968bfe23.png)

**Comment by LEOkonami** [comment]
@snipe The messages are empty, I can't see any error...
![image](https://user-images.githubusercontent.com/39458766/103630632-9facac80-4f4a-11eb-8f4a-a206a9f58d72.png)

**Comment by LEOkonami** [comment]
@snipe @GustelDE Any updates about this issue, super annoying :)

**Comment by DPNADM** [comment]
I am having this same issue in 5.1.4.

It will not progress to the next asset ID.  I have to manually change it.  In the admin settings, I cannot set it to use a higher number, it just falls back.  No changes I make to the auto-increment settings will stick.

**Comment by Viiviv** [comment]
Having issues with auto-increment too. Seems to be stuck in an used tag.
Also changing the next auto-increment in the menu doesn't change in the UI. 
It does however change in the database settings next_auto_tag_base

Version v5.1.4 - build 5886

**Comment by DPNADM** [comment]
I have this same issue.  I'm updated up to v5.1.8 - build 6227 and the issue persists.  I've had this issue ever since upgrading to 5.1.4 which was my first 5.x version.  In the admin settings within the GUI, I cannot even set the settings for the incrementing asset tag.  Any changes are reverted and not stored.

I am wondering if there is some sort of permission issue here.  I can't seem to change some other admin settings since the update either.  Any changes revert back.  I do not see error messages when I attempt to change and save.  Going back into the setting that was changed just shows the previous settings are still set.

There are no issues adding assets, models, or other items to Snipe-IT...just changes to the admin settings appear to be an issue.

**Comment by DPNADM** [comment]
Actually, I was able to resolve just by using the commands in the "common issues" documentation.

https://snipe-it.readme.io/docs/common-issues

composer dump-autoload
php artisan cache:clear 
php artisan config:clear
php artisan route:clear
php artisan debugbar:clear
php artisan event:clear
php artisan view:clear
php artisan optimize:clear
php artisan clear-compiled


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.Or to run them as a one-liner all at once:These commands clear out cached service files that help speed up modern PHP applications but can a...</div></blockquote>

**Comment by LEOkonami** [comment]
I fixed the issue with some Github login and shit, not sure anymore what I did it just worked.
