### ISSUE TITLE
Error: undefined when sending test mail with SMTP Relay (no User/Pass)

### ISSUE THREAD

**Issue by JovinJovinsson** [grokability/snipe-it#8620]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
At the company I work for we have an SMTP relay which has a whitelist of servers that can send emails. It does not accept username & password authentication. I have tried leaving the MAIL_USERNAME and MAIL_PASSWORD fields blank, or set to null however it continues to provide the "Error: undefined".
In a previous project we used "PHPMailer" and that works fine without setting a Username & Password

**To Reproduce**
1. Go to Settings -> General
2. Click on Send Test
3. See error

**Expected behavior**
The email should be sent successfully and received in the targeted inbox

**Screenshots**
Due to company information no screenshots can be provided, however I'll provide code dumps below.

**Server (please complete the following information):**
 - Snipe-IT Version 4.9.4
 - OS: CentOS RHEL7
 - Web Server: NGINX
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.111

**Error Messages**
```
Expected response code 220 but got code "500", with message "500 5.3.3 Unrecognized command "
/var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php#457
Swift_TransportException
        }

        if (!$valid) {
            $this->throwException(new Swift_TransportException('Expected response code '.implode('/', $wanted).' but got code "'.$code.'", with message "'.$response.'"', $code));
        }
    }


#0 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(346): Swift_Transport_EsmtpTransport->executeCommand()
#3 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#4 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(64): Illuminate\Mail\Mailer->send()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\Notifications\NotificationSender->send()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Notifications\ChannelManager->send()
#13 /var/www/app/Http/Controllers/Api/SettingsController.php(136): Illuminate\Support\Facades\Facade::__callStatic()
#14 [internal function]: App\Http\Controllers\Api\SettingsController->ajaxTestEmail()
#15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch()
#18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#20 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#22 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#25 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Cors\HandleCors->handle()
#26 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#28 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Auth\Middleware\Authenticate->handle()
#29 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#31 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then()
#32 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack()
#33 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute()
#34 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\Routing\Router->dispatchToRoute()
#35 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch()
#36 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#37 /var/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#38 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#39 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#41 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\SecurityHeaders->handle()
#42 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#44 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#45 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\CheckForDebug->handle()
#48 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#50 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\CheckForSetup->handle()
#51 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle()
#54 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#56 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#57 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#59 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle()
#60 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#62 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#63 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#65 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Cors\HandlePreflight->handle()
#66 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#68 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then()
#69 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#70 /var/www/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#71 {main}
```

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What method you used to install Snipe-IT - Manual
- Everything else in the installation worked without issue
- No data has been edited directly in the database
- Here is my .env (yes I know it's unusual using Port 25 with TLS, but that's what my company uses)
- The email is a legitimate email, but I've just obfuscated it

```
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.ent.company.net
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=from@company.net
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=from@company.net
MAIL_REPLYTO_NAME='PSS LOOT System'
MAIL_BACKUP_NOTIFICATION_ADDRESS=jovinjovinsson@company.net
```

**Comment by JovinJovinsson** [comment]
Additionally, I have confirmed that using PHPMailer I can send an email from the server without authentication.

**Comment by snipe** [comment]
Can you try just using the `mail` driver and letting PHP handle the sending of email?

**Comment by JovinJovinsson** [comment]
Not sure how to get it to use the `mail `driver instead of SwiftMailer/Laravel, but I just went into the `vendor/laraval/framework/src/Illuminate/Notifications/Channels/MailChannel.php` and modified the `send()` function to direct to `PHPMailer` instead.

Works a treat

**Comment by snipe** [comment]
Please never ever edit vendor files. That’s a footgun. Next time we update packages, your changes will be overwritten, and we’ll be right back where we are now.

Use `mail` instead of `smtp` as your mail driver.

**Comment by JovinJovinsson** [comment]
Changing the driver to `mail` does not produce an error in the logs however it also does not actually send anything, I'll have to stick to my modification of the vendor files and use Git to merge in new versions of the system when we upgrade. It's all behind a proxy/firewall and access is only provisioned when I provide it so no auto-updates possible anyway.

Thanks for the warning :)

**Comment by luanche** [comment]
> Can you try just using the `mail` driver and letting PHP handle the sending of email?

Hello, is that means just change the driver to mail in .env file? Do I need configure another thing additional.

**Comment by snipe** [comment]
@luanche this has been fixed in the past version or two

**Comment by luanche** [comment]
Hello @snipe, thanks for your reply. I try the `mail` driver and `smtp` driver, but still not work with errors.
`smtp`: Connection could not be established with host smtp.company.org :stream_socket_client(): unable to connect to smtp.company.org:25 (Permission denied)
`mail`: Expected response code 220 but got an empty response

This is my .env file mail settings:
`MAIL_DRIVER=smtp`
`MAIL_HOST=smtp.company.org`
`MAIL_PORT=25`
`MAIL_USERNAME=`
`MAIL_PASSWORD=`
`MAIL_ENCRYPTION=null`
`MAIL_FROM_ADDR=user-name@company.com`
`MAIL_FROM_NAME='SnipeIT'`
`MAIL_REPLYTO_ADDR=user-name@company.com`
`MAIL_REPLYTO_NAME='Snipe-IT'`
`MAIL_AUTO_EMBED_METHOD='attachment'`

**Comment by luanche** [comment]
by the way, my snipeit version is `v5.1.2` and PHP version is `7.4.15`

**Comment by luanche** [comment]
I already figure out this issue, it's because of linux sebool.

`setsebool -P httpd_can_network_connect 1`
`setsebool -P httpd_can_sendmail 1`

Thanks a lot.
