### ISSUE TITLE
ldap got disabled after upgrading to 5.04 from 4.9.5

### ISSUE THREAD

**Issue by shoebwk** [grokability/snipe-it#8657]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

ldap sync should be working as previous version
-----

#### Actual Behavior

ldap user not visible, when try to sync gets 500 error, when try to test ldap from admin panel get the message **ldap is not enabled, cannot test**

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**_ldap user not visible, when try to sync gets 500 error, when try to test ldap from admin panel get the message **ldap is not enabled, cannot test**_**

**Comment by steve1673** [comment]
Adding a +1 to this, I'm also seeing this issue. If the OP doesn't respond, I can look at adding my troubleshooting info.

**Comment by uberbrady** [comment]
This usually means that you don't have the php-ldap extension enabled. I would probably only expect that if you had **also** changed your PHP version while you did the upgrade, and in that process accidentally missed the LDAP extension.

Can either of you check that and see? `php -i` isn't a perfect test, but running that and piping it with something like `|grep -i ldap` should give you something. If it is at least definitely installed on the command-line (sometimes command-line PHP and webserver PHP are different, which really sucks :( ) you should at least be able to run the Artisan CLI via `php artisan snipeit:ldap-sync` - and that should work. Then you would just need to figure out how to either install the php-ldap extension, or possibly 'enable' it using `php.ini`.

@steve1673 I'd be happy to see troubleshooting info; more info is almost always better.

**Comment by steve1673** [comment]
basic install info: 

- Windows install on server 2019 / IIS. 
- Debug not turned on yet, I'm trying to figure that out now. (sorry, i'm more of a hardware guy, this isn't as intuitive for me)
- Upgraded last week from 4.9.5 to 5.0.4. System was working fine for months prior to this. 
- upgrade was via php upgrade..php with no other changes made. I didn't check LDAP at that point, as everything else looked like it was working OK. (I should have checked in more detail)
- MariaDB version 10.5.5

php.ini and php -i results attached. 
[php.ini.txt](https://github.com/snipe/snipe-it/files/5477343/php.ini.txt)
[php -i.txt](https://github.com/snipe/snipe-it/files/5477352/php.-i.txt)

**Comment by shoebwk** [comment]
> This usually means that you don't have the php-ldap extension enabled. I would probably only expect that if you had **also** changed your PHP version while you did the upgrade, and in that process accidentally missed the LDAP extension.
> 
> Can either of you check that and see? `php -i` isn't a perfect test, but running that and piping it with something like `|grep -i ldap` should give you something. If it is at least definitely installed on the command-line (sometimes command-line PHP and webserver PHP are different, which really sucks :( ) you should at least be able to run the Artisan CLI via `php artisan snipeit:ldap-sync` - and that should work. Then you would just need to figure out how to either install the php-ldap extension, or possibly 'enable' it using `php.ini`.
> 
> @steve1673 I'd be happy to see troubleshooting info; more info is almost always better.
no PHP version was changed, did upgrade directly from GITHUB php upgrade.php. everything was working in 4.9.5. Can't run these commands since I restored my VM snapshot back to 4.9.5

**Comment by snipe** [comment]
@uberbrady I wouldn't *think* that would be the reason. In v4, we checked to see whether or not the ldap functions existed. If they didn't (meaning php-ldap wasn't installed), you'd see that **ldap is not enabled, cannot test** message. 

Can we see screenshots of your LDAP settings page (with sensitive info redacted, of course)

**Comment by steve1673** [comment]
Sure thing. Items to note: 
- LDAP show enabled in the first checkbox. 
- LDAP test fails as LDAP is not enabled. 
- Attempting to make a change and save results in server error 500. 

![image](https://user-images.githubusercontent.com/4225758/97913022-54d8a380-1d13-11eb-8fa3-713c3a206dde.png)

**Comment by snipe** [comment]
It looks like that error is triggered by:

```php
if(!$ldap->init()) {
            Log::info('LDAP is not enabled cannot test.');
            return response()->json(['message' => 'LDAP is not enabled, cannot test.'], 400);
}
```

So something is going wrong with the LDAP init process.

**Comment by uberbrady** [comment]
> It looks like that error is triggered by:
> 
> ```
> if(!$ldap->init()) {
>             Log::info('LDAP is not enabled cannot test.');
>             return response()->json(['message' => 'LDAP is not enabled, cannot test.'], 400);
> }
> ```
> 
> So something is going wrong with the LDAP init process.

Yeah, I agree :/ - 

@steve1673 can you get us your `laravel.log` file? Usually in `storage/logs/laravel.log`. Maybe a missing migration? But I'd expect stuff to blow up all over the place if that were the case.

**Comment by snipe** [comment]
> I'd expect stuff to blow up all over the place if that were the case.

I'd expect that too, tbh. The LDAP migrations were a while back.

**Comment by steve1673** [comment]
[laravel.log](https://github.com/snipe/snipe-it/files/5477827/laravel.log)

**Comment by snipe** [comment]
```php
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ad_append_domain' in 'field list' at C:\\inetpub\\wwwroot\\snipe-it\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:64)
[stacktrace]
```

Did you run migrations? 

```
php artisan migrate
```

**Comment by steve1673** [comment]
not since I migrated to this server. I can run it now if you need me to

**Comment by snipe** [comment]
Please do and try your LDAP again

**Comment by steve1673** [comment]
C:\inetpub\wwwroot\snipe-it>php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2018_07_28_023826_create_checkout_acceptances_table

In Connection.php line 669:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists (SQL: create t
  able `checkout_acceptances` (`id` int unsigned not null auto_increment primary key, `checkoutable_type` varchar(191
  ) not null, `checkoutable_id` bigint unsigned not null, `assigned_to_id` int unsigned not null, `signature_filename
  ` varchar(191) null, `accepted_at` timestamp null, `declined_at` timestamp null, `created_at` timestamp null, `upda
  ted_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' eng
  ine = InnoDB)


In PDOStatement.php line 129:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists


In PDOStatement.php line 127:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists

no change to LDAP.

**Comment by snipe** [comment]
Uggggh.... means your migrations table is donked. (There's nothing *we* do to donk it, mind you. We only ever write to that table, never ever delete from it.)

Can you show me the contents of your `migrations` table?

**Comment by steve1673** [comment]
hopefully this is what you're looking for. We're a little out of my comfort zone working with databases, so feel free to point me in the right direction is this is incorrect. 

[migrations.xlsx](https://github.com/snipe/snipe-it/files/5477899/migrations.xlsx)

**Comment by snipe** [comment]
You have 278 migrations, where you should have 291. My guess would be something somehow failed the first time that 2018_07_28_023826_create_checkout_acceptances_table migration was run. 

Are you using a GUI, or... how are you interfacing with mysql?

**Comment by steve1673** [comment]
HeidiSQL - https://www.heidisql.com/
the instructions I followed to set this up on windows / IIS are here: https://blog.teknex.com.au/snipe-it/snipe-it-installation-on-windows-server/

if the date you quoted is correct, then that was the previous install of snipe-it on an older server in AWS. we recently migrated to an azure Windows VM a few months ago. We didn't see any LDAP issues until the migration to Ver. 5 of Snipe-it. 

I'm stepping away for a few hours shortly. if there are any other logs of data you need before then, please let me know. 

<blockquote><div><strong><a href="https://www.heidisql.com/">HeidiSQL - MariaDB, MySQL, MSSQL, PostgreSQL and SQLite made easy</a></strong></div><div>HeidiSQL is a free and powerful client for MariaDB, MySQL, Microsoft SQL Server, PostgreSQL and SQLite</div></blockquote>
<blockquote><img src="https://blog.teknex.com.au/wp-content/uploads/2019/08/SnipeOnWindowsFeaturedImage.jpg" width="48" align="right"><div>Teknex</div><div><strong><a href="https://blog.teknex.com.au/snipe-it/snipe-it-installation-on-windows-server/">SNIPE-IT Installation On Windows Server</a></strong></div><div>In this detailed tutorial, we will go through all the required steps needed to be performed in order to successfully install Snipe-IT on Windows Server 2019. This blog is updated on 10 Jul 2020. Make sure you install Visual C++ 2017 Redistributable if you are planning to use PHP Version 7.4.6 or higher This post [&hellip;]</div></blockquote>

**Comment by henningkessler** [comment]
I had the same error messages and problems while I tried my migration from 4.9.3 to 5.0.3. This installation is running in a jail on FreeBSD 11.3. Unfortunately I already reverted to a snapshot as my maintenance window was closing...

**Comment by snipe** [comment]
> We didn't see any LDAP issues until the migration to Ver. 5 of Snipe-it.

The date is just when the migration file was created. LDAP isn't working for you now because there were migrations that happened after that one that impact LDAP, but because it short-circuits at that one, they never run.

Try inserting a new record in the migrations table via your GUI where the `migration` field is `2018_07_28_023826_create_checkout_acceptances_table` and `batch` is 5, then try running your migrations again.

**Comment by steve1673** [comment]
looks like it fixed something, but there are more errors
LDAP status is unchanged

php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > y

Migrating: 2018_08_20_204842_add_depreciation_option_to_settings
Migrated:  2018_08_20_204842_add_depreciation_option_to_settings (0.02 seconds)
Migrating: 2018_09_10_082212_create_checkout_acceptances_for_unaccepted_assets
Migrated:  2018_09_10_082212_create_checkout_acceptances_for_unaccepted_assets (0.01 seconds)
Migrating: 2018_10_18_191228_add_kits_licenses_table

In Connection.php line 669:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kits_licenses' already exists (SQL: create table `k
  its_licenses` (`id` int unsigned not null auto_increment primary key, `kit_id` int null, `license_id` int null, `qu
  antity` int not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set u
  tf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)


In PDOStatement.php line 129:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kits_licenses' already exists


In PDOStatement.php line 127:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kits_licenses' already exists

**Comment by snipe** [comment]
Further along, but yeesh... no idea how your migrations table got so mangled.

Now try inserting migration as `2018_10_18_191228_add_kits_licenses_table` and `batch` as whatever the highest batch number in your migrations table is, and re-run migrations.

**Comment by steve1673** [comment]
got ar error with "1050 Table 'kits' already exists" this time. 
can I assume that I need to follow your syntax for adding a line to the table for each of these errors? I can run through them all without having to converse over each one if that's the case

**Comment by snipe** [comment]
Yeah, you basically want to work through the migrations one by one so that your table looks like this. (The batch number doesn't matter really, nor does the ID of the row itself. The ID of the row itself will auto-increment, so no need to give it a value at all.)

```
1	2012_12_06_225921_migration_cartalyst_sentry_install_users	1
2	2012_12_06_225929_migration_cartalyst_sentry_install_groups	1
3	2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot	1
4	2012_12_06_225988_migration_cartalyst_sentry_install_throttle	1
5	2013_03_23_193214_update_users_table	1
6	2013_11_13_075318_create_models_table	1
7	2013_11_13_075335_create_categories_table	1
8	2013_11_13_075347_create_manufacturers_table	1
9	2013_11_15_015858_add_user_id_to_categories	1
10	2013_11_15_112701_add_user_id_to_manufacturers	1
11	2013_11_15_190327_create_assets_table	1
12	2013_11_15_190357_create_licenses_table	1
13	2013_11_15_201848_add_license_name_to_licenses	1
14	2013_11_16_040323_create_depreciations_table	1
15	2013_11_16_042851_add_depreciation_id_to_models	1
16	2013_11_16_084923_add_user_id_to_models	1
17	2013_11_16_103258_create_locations_table	1
18	2013_11_16_103336_add_location_id_to_assets	1
19	2013_11_16_103407_add_checkedout_to_to_assets	1
20	2013_11_16_103425_create_history_table	1
21	2013_11_17_054359_drop_licenses_table	1
22	2013_11_17_054526_add_physical_to_assets	1
23	2013_11_17_055126_create_settings_table	1
24	2013_11_17_062634_add_license_to_assets	1
25	2013_11_18_134332_add_contacts_to_users	1
26	2013_11_18_142847_add_info_to_locations	1
27	2013_11_18_152942_remove_location_id_from_asset	1
28	2013_11_18_164423_set_nullvalues_for_user	1
29	2013_11_19_013337_create_asset_logs_table	1
30	2013_11_19_061409_edit_added_on_asset_logs_table	1
31	2013_11_19_062250_edit_location_id_asset_logs_table	1
32	2013_11_20_055822_add_soft_delete_on_assets	1
33	2013_11_20_121404_add_soft_delete_on_locations	1
34	2013_11_20_123137_add_soft_delete_on_manufacturers	1
35	2013_11_20_123725_add_soft_delete_on_categories	1
36	2013_11_20_130248_create_status_labels	1
37	2013_11_20_130830_add_status_id_on_assets_table	1
38	2013_11_20_131544_add_status_type_on_status_labels	1
39	2013_11_20_134103_add_archived_to_assets	1
40	2013_11_21_002321_add_uploads_table	1
41	2013_11_21_024531_remove_deployable_boolean_from_status_labels	1
42	2013_11_22_075308_add_option_label_to_settings_table	1
43	2013_11_22_213400_edits_to_settings_table	1
44	2013_11_25_013244_create_licenses_table	1
45	2013_11_25_031458_create_license_seats_table	1
46	2013_11_25_032022_add_type_to_actionlog_table	1
47	2013_11_25_033008_delete_bad_licenses_table	1
48	2013_11_25_033131_create_new_licenses_table	1
49	2013_11_25_033534_add_licensed_to_licenses_table	1
50	2013_11_25_101308_add_warrantee_to_assets_table	1
51	2013_11_25_104343_alter_warranty_column_on_assets	1
52	2013_11_25_150450_drop_parent_from_categories	1
53	2013_11_25_151920_add_depreciate_to_assets	1
54	2013_11_25_152903_add_depreciate_to_licenses_table	1
55	2013_11_26_211820_drop_license_from_assets_table	1
56	2013_11_27_062510_add_note_to_asset_logs_table	1
57	2013_12_01_113426_add_filename_to_asset_log	1
58	2013_12_06_094618_add_nullable_to_licenses_table	1
59	2013_12_10_084038_add_eol_on_models_table	1
60	2013_12_12_055218_add_manager_to_users_table	1
61	2014_01_28_031200_add_qr_code_to_settings_table	1
62	2014_02_13_183016_add_qr_text_to_settings_table	1
63	2014_05_24_093839_alter_default_license_depreciation_id	1
64	2014_05_27_231658_alter_default_values_licenses	1
65	2014_06_19_191508_add_asset_name_to_settings	1
66	2014_06_20_004847_make_asset_log_checkedout_to_nullable	1
67	2014_06_20_005050_make_asset_log_purchasedate_to_nullable	1
68	2014_06_24_003011_add_suppliers	1
69	2014_06_24_010742_add_supplier_id_to_asset	1
70	2014_06_24_012839_add_zip_to_supplier	1
71	2014_06_24_033908_add_url_to_supplier	1
72	2014_07_08_054116_add_employee_id_to_users	1
73	2014_07_09_134316_add_requestable_to_assets	1
74	2014_07_17_085822_add_asset_to_software	1
75	2014_07_17_161625_make_asset_id_in_logs_nullable	1
76	2014_08_12_053504_alpha_0_4_2_release	1
77	2014_08_17_083523_make_location_id_nullable	1
78	2014_10_16_200626_add_rtd_location_to_assets	1
79	2014_10_24_000417_alter_supplier_state_to_32	1
80	2014_10_24_015641_add_display_checkout_date	1
81	2014_10_28_222654_add_avatar_field_to_users_table	1
82	2014_10_29_045924_add_image_field_to_models_table	1
83	2014_11_01_214955_add_eol_display_to_settings	1
84	2014_11_04_231416_update_group_field_for_reporting	1
85	2014_11_05_212408_add_fields_to_licenses	1
86	2014_11_07_021042_add_image_to_supplier	1
87	2014_11_20_203007_add_username_to_user	1
88	2014_11_20_223947_add_auto_to_settings	1
89	2014_11_20_224421_add_prefix_to_settings	1
90	2014_11_21_104401_change_licence_type	1
91	2014_12_09_082500_add_fields_maintained_term_to_licenses	1
92	2015_02_04_155757_increase_user_field_lengths	1
93	2015_02_07_013537_add_soft_deleted_to_log	1
94	2015_02_10_040958_fix_bad_assigned_to_ids	1
95	2015_02_10_053310_migrate_data_to_new_statuses	1
96	2015_02_11_044104_migrate_make_license_assigned_null	1
97	2015_02_11_104406_migrate_create_requests_table	1
98	2015_02_12_001312_add_mac_address_to_asset	1
99	2015_02_12_024100_change_license_notes_type	1
100	2015_02_17_231020_add_localonly_to_settings	1
101	2015_02_19_222322_add_logo_and_colors_to_settings	1
102	2015_02_24_072043_add_alerts_to_settings	1
103	2015_02_25_022931_add_eula_fields	1
104	2015_02_25_204513_add_accessories_table	1
105	2015_02_26_091228_add_accessories_user_table	1
106	2015_02_26_115128_add_deleted_at_models	1
107	2015_02_26_233005_add_category_type	1
108	2015_03_01_231912_update_accepted_at_to_acceptance_id	1
109	2015_03_05_011929_add_qr_type_to_settings	1
110	2015_03_18_055327_add_note_to_user	1
111	2015_04_29_234704_add_slack_to_settings	1
112	2015_05_04_085151_add_parent_id_to_locations_table	1
113	2015_05_22_124421_add_reassignable_to_licenses	1
114	2015_06_10_003314_fix_default_for_user_notes	1
115	2015_06_10_003554_create_consumables	1
116	2015_06_15_183253_move_email_to_username	1
117	2015_06_23_070346_make_email_nullable	1
118	2015_06_26_213716_create_asset_maintenances_table	1
119	2015_07_04_212443_create_custom_fields_table	1
120	2015_07_09_014359_add_currency_to_settings_and_locations	1
121	2015_07_21_122022_add_expected_checkin_date_to_asset_logs	1
122	2015_07_24_093845_add_checkin_email_to_category_table	1
123	2015_07_25_055415_remove_email_unique_constraint	1
124	2015_07_29_230054_add_thread_id_to_asset_logs_table	1
125	2015_07_31_015430_add_accepted_to_assets	1
126	2015_09_09_195301_add_custom_css_to_settings	1
127	2015_09_21_235926_create_custom_field_custom_fieldset	1
128	2015_09_22_000104_create_custom_fieldsets	1
129	2015_09_22_003321_add_fieldset_id_to_assets	1
130	2015_09_22_003413_migrate_mac_address	1
131	2015_09_28_003314_fix_default_purchase_order	1
132	2015_10_01_024551_add_accessory_consumable_price_info	1
133	2015_10_12_192706_add_brand_to_settings	1
134	2015_10_22_003314_fix_defaults_accessories	1
135	2015_10_23_182625_add_checkout_time_and_expected_checkout_date_to_assets	1
136	2015_11_05_061015_create_companies_table	1
137	2015_11_05_061115_add_company_id_to_consumables_table	1
138	2015_11_05_183749_image	1
139	2015_11_06_092038_add_company_id_to_accessories_table	1
140	2015_11_06_100045_add_company_id_to_users_table	1
141	2015_11_06_134742_add_company_id_to_licenses_table	1
142	2015_11_08_035832_add_company_id_to_assets_table	1
143	2015_11_08_222305_add_ldap_fields_to_settings	1
144	2015_11_15_151803_add_full_multiple_companies_support_to_settings_table	1
145	2015_11_26_195528_import_ldap_settings	1
146	2015_11_30_191504_remove_fk_company_id	1
147	2015_12_21_193006_add_ldap_server_cert_ignore_to_settings_table	1
148	2015_12_30_233509_add_timestamp_and_userId_to_custom_fields	1
149	2015_12_30_233658_add_timestamp_and_userId_to_custom_fieldsets	1
150	2016_01_28_041048_add_notes_to_models	1
151	2016_02_19_070119_add_remember_token_to_users_table	1
152	2016_02_19_073625_create_password_resets_table	1
153	2016_03_02_193043_add_ldap_flag_to_users	1
154	2016_03_02_220517_update_ldap_filter_to_longer_field	1
155	2016_03_08_225351_create_components_table	1
156	2016_03_09_024038_add_min_stock_to_tables	1
157	2016_03_10_133849_add_locale_to_users	1
158	2016_03_10_135519_add_locale_to_settings	1
159	2016_03_11_185621_add_label_settings_to_settings	1
160	2016_03_22_125911_fix_custom_fields_regexes	1
161	2016_04_28_141554_add_show_to_users	1
162	2016_05_16_164733_add_model_mfg_to_consumable	1
163	2016_05_19_180351_add_alt_barcode_settings	1
164	2016_05_19_191146_add_alter_interval	1
165	2016_05_19_192226_add_inventory_threshold	1
166	2016_05_20_024859_remove_option_keys_from_settings_table	1
167	2016_05_20_143758_remove_option_value_from_settings_table	1
168	2016_06_01_000001_create_oauth_auth_codes_table	1
169	2016_06_01_000002_create_oauth_access_tokens_table	1
170	2016_06_01_000003_create_oauth_refresh_tokens_table	1
171	2016_06_01_000004_create_oauth_clients_table	1
172	2016_06_01_000005_create_oauth_personal_access_clients_table	1
173	2016_06_01_140218_add_email_domain_and_format_to_settings	1
174	2016_06_22_160725_add_user_id_to_maintenances	1
175	2016_07_13_150015_add_is_ad_to_settings	1
176	2016_07_14_153609_add_ad_domain_to_settings	1
177	2016_07_22_003348_fix_custom_fields_regex_stuff	1
178	2016_07_22_054850_one_more_mac_addr_fix	1
179	2016_07_22_143045_add_port_to_ldap_settings	1
180	2016_07_22_153432_add_tls_to_ldap_settings	1
181	2016_07_27_211034_add_zerofill_to_settings	1
182	2016_08_02_124944_add_color_to_statuslabel	1
183	2016_08_04_134500_add_disallow_ldap_pw_sync_to_settings	1
184	2016_08_09_002225_add_manufacturer_to_licenses	1
185	2016_08_12_121613_add_manufacturer_to_accessories_table	1
186	2016_08_23_143353_add_new_fields_to_custom_fields	1
187	2016_08_23_145619_add_show_in_nav_to_status_labels	1
188	2016_08_30_084634_make_purchase_cost_nullable	1
189	2016_09_01_141051_add_requestable_to_asset_model	1
190	2016_09_02_001448_create_checkout_requests_table	1
191	2016_09_04_180400_create_actionlog_table	1
192	2016_09_04_182149_migrate_asset_log_to_action_log	1
193	2016_09_19_235935_fix_fieldtype_for_target_type	1
194	2016_09_23_140722_fix_modelno_in_consumables_to_string	1
195	2016_09_28_231359_add_company_to_logs	1
196	2016_10_14_130709_fix_order_number_to_varchar	1
197	2016_10_16_015024_rename_modelno_to_model_number	1
198	2016_10_16_015211_rename_consumable_modelno_to_model_number	1
199	2016_10_16_143235_rename_model_note_to_notes	1
200	2016_10_16_165052_rename_component_total_qty_to_qty	1
201	2016_10_19_145520_fix_order_number_in_components_to_string	1
202	2016_10_27_151715_add_serial_to_components	1
203	2016_10_27_213251_increase_serial_field_capacity	1
204	2016_10_29_002724_enable_2fa_fields	1
205	2016_10_29_082408_add_signature_to_acceptance	1
206	2016_11_01_030818_fix_forgotten_filename_in_action_logs	1
207	2016_11_13_020954_rename_component_serial_number_to_serial	1
208	2016_11_16_172119_increase_purchase_cost_size	1
209	2016_11_17_161317_longer_state_field_in_location	1
210	2016_11_17_193706_add_model_number_to_accessories	1
211	2016_11_24_160405_add_missing_target_type_to_logs_table	1
212	2016_12_07_173720_increase_size_of_state_in_suppliers	1
213	2016_12_19_004212_adjust_locale_length_to_10	1
214	2016_12_19_133936_extend_phone_lengths_in_supplier_and_elsewhere	1
215	2016_12_27_212631_make_asset_assigned_to_polymorphic	1
216	2017_01_09_040429_create_locations_ldap_query_field	1
217	2017_01_14_002418_create_imports_table	1
218	2017_01_25_063357_fix_utf8_custom_field_column_names	1
219	2017_03_03_154632_add_time_date_display_to_settings	1
220	2017_03_10_210807_add_fields_to_manufacturer	1
221	2017_05_08_195520_increase_size_of_field_values_in_custom_fields	1
222	2017_05_22_204422_create_departments	1
223	2017_05_22_233509_add_manager_to_locations_table	1
224	2017_06_14_122059_add_next_autoincrement_to_settings	1
225	2017_06_18_151753_add_header_and_first_row_to_importer_table	1
226	2017_07_07_191533_add_login_text	1
227	2017_07_25_130710_add_thumbsize_to_settings	1
228	2017_08_03_160105_set_asset_archived_to_zero_default	1
229	2017_08_22_180636_add_secure_password_options	1
230	2017_08_25_074822_add_auditing_tables	1
231	2017_08_25_101435_add_auditing_to_settings	1
232	2017_09_18_225619_fix_assigned_type_not_being_nulled	1
233	2017_10_03_015503_drop_foreign_keys	1
234	2017_10_10_123504_allow_nullable_depreciation_id_in_models	1
235	2017_10_17_133709_add_display_url_to_settings	1
236	2017_10_19_120002_add_custom_forgot_password_url	1
237	2017_10_19_130406_add_image_and_supplier_to_accessories	1
238	2017_10_20_234129_add_location_indices_to_assets	1
239	2017_10_25_202930_add_images_uploads_to_locations_manufacturers_etc	1
240	2017_10_27_180947_denorm_asset_locations	1
241	2017_10_27_192423_migrate_denormed_asset_locations	1
242	2017_10_30_182938_add_address_to_user	1
243	2017_11_08_025918_add_alert_menu_setting	1
244	2017_11_08_123942_labels_display_company_name	1
245	2017_12_12_010457_normalize_asset_last_audit_date	1
246	2017_12_12_033618_add_actionlog_meta	1
247	2017_12_26_170856_re_normalize_last_audit	1
248	2018_01_17_184354_add_archived_in_list_setting	1
249	2018_01_19_203121_add_dashboard_message_to_settings	1
250	2018_01_24_062633_add_footer_settings_to_settings	1
251	2018_01_24_093426_add_modellist_preferenc	1
252	2018_02_22_160436_add_remote_user_settings	1
253	2018_03_03_011032_add_theme_to_settings	1
254	2018_03_06_054937_add_default_flag_on_statuslabels	1
255	2018_03_23_212048_add_display_in_email_to_custom_fields	1
256	2018_03_24_030738_add_show_images_in_email_setting	1
257	2018_03_24_050108_add_cc_alerts	1
258	2018_03_29_053618_add_canceled_at_and_fulfilled_at_in_requests	1
259	2018_03_29_070121_add_drop_unique_requests	1
260	2018_03_29_070511_add_new_index_requestable	1
261	2018_04_02_150700_labels_display_model_name	1
262	2018_04_16_133902_create_custom_field_default_values_table	1
263	2018_05_04_073223_add_category_to_licenses	1
264	2018_05_04_075235_add_update_license_category	1
265	2018_05_08_031515_add_gdpr_privacy_footer	1
266	2018_05_14_215229_add_indexes	1
267	2018_05_14_223646_add_indexes_to_assets	1
268	2018_05_14_233638_denorm_counters_on_assets	1
269	2018_05_16_153409_add_first_counter_totals_to_assets	1
270	2018_06_21_134622_add_version_footer	1
271	2018_07_05_215440_add_unique_serial_option_to_settings	1
272	2018_07_17_005911_create_login_attempts_table	1
273	2018_07_24_154348_add_logo_to_print_assets	1
274	2019_02_14_154310_change_auto_increment_prefix_to_nullable	1
275	2019_02_16_143518_auto_increment_back_to_string	1
276	2019_02_20_234421_make_serial_nullable	1
277	2019_02_21_224703_make_fields_nullable_for_integrity	1
278	2019_06_12_184327_rename_groups_table	1
279	2018_07_28_023826_create_checkout_acceptances_table	2
280	2018_08_20_204842_add_depreciation_option_to_settings	2
281	2018_09_10_082212_create_checkout_acceptances_for_unaccepted_assets	2
282	2018_10_18_191228_add_kits_licenses_table	2
283	2018_10_19_153910_add_kits_table	2
284	2018_10_19_154013_add_kits_models_table	2
285	2018_12_05_211936_add_favicon_to_settings	2
286	2018_12_05_212119_add_email_logo_to_settings	2
287	2019_02_07_185953_add_kits_consumables_table	2
288	2019_02_07_190030_add_kits_accessories_table	2
289	2019_02_12_182750_add_actiondate_to_actionlog	2
290	2019_02_17_205048_add_label_logo_to_settings	2
291	2019_07_23_140906_add_show_assigned_assets_to_settings	2
292	2019_08_20_084049_add_custom_remote_user_header	2
293	2019_12_04_223111_passport_upgrade	2
294	2020_02_04_172100_add_ad_append_domain_settings	2
295	2020_04_29_222305_add_saml_fields_to_settings	2
296	2020_10_22_233743_move_accessory_checkout_note_to_join_table	3
297	2020_10_23_161736_fix_zero_values_for_locations	3
```

Each time you run into a table or column doesn't exist error, just manually add whatever that migration is into the database and re-run migrations until you hit the next error or "Nothing to migrate"

**Comment by steve1673** [comment]
gotcha. TY back in a bit.

**Comment by steve1673** [comment]
fixed the following:
2018_10_19_153910_add_kits_table
2018_10_19_154013_add_kits_models_table
2019_02_07_185953_add_kits_consumables_table
2019_02_07_190030_add_kits_accessories_table

LDAP is now functional, and all users are visible! 

TY for all of your help. Good luck trying to figure out why others have had this issue with migration, Ping me here if there's any info I can provide that may help.

**Comment by snipe** [comment]
Glad you're sorted, @steve1673!

@shoebwk any updates?

**Comment by henningkessler** [comment]
I tried the same approach but altering the migration tables did not fixed the problem  for me still getting:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ad_append_domain' in 'field list' (SQL: update `settings` set `ad_append_domain` = 0, `settings`.`updated_at` = 2020-11-06 14:54:42 where `id` = 1)
```
if I try to test LDAP

this is what I did to my migrations table:
```
INSERT INTO `migrations` VALUES (1,'2012_12_06_225921_migration_cartalyst_sentry_install_users',1), 
(2,'2012_12_06_225929_migration_cartalyst_sentry_install_groups',1), 
(3,'2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot',1), 
(4,'2012_12_06_225988_migration_cartalyst_sentry_install_throttle',1), 
(5,'2013_03_23_193214_update_users_table',1), 
(6,'2013_11_13_075318_create_models_table',1), 
(7,'2013_11_13_075335_create_categories_table',1), 
(8,'2013_11_13_075347_create_manufacturers_table',1), 
(9,'2013_11_15_015858_add_user_id_to_categories',1), 
(10,'2013_11_15_112701_add_user_id_to_manufacturers',1), 
(11,'2013_11_15_190327_create_assets_table',1), 
(12,'2013_11_15_190357_create_licenses_table',1), 
(13,'2013_11_15_201848_add_license_name_to_licenses',1), 
(14,'2013_11_16_040323_create_depreciations_table',1), 
(15,'2013_11_16_042851_add_depreciation_id_to_models',1), 
(16,'2013_11_16_084923_add_user_id_to_models',1), 
(17,'2013_11_16_103258_create_locations_table',1), 
(18,'2013_11_16_103336_add_location_id_to_assets',1), 
(19,'2013_11_16_103407_add_checkedout_to_to_assets',1), 
(20,'2013_11_16_103425_create_history_table',1), 
(21,'2013_11_17_054359_drop_licenses_table',1), 
(22,'2013_11_17_054526_add_physical_to_assets',1), 
(23,'2013_11_17_055126_create_settings_table',1), 
(24,'2013_11_17_062634_add_license_to_assets',1), 
(25,'2013_11_18_134332_add_contacts_to_users',1), 
(26,'2013_11_18_142847_add_info_to_locations',1), 
(27,'2013_11_18_152942_remove_location_id_from_asset',1), 
(28,'2013_11_18_164423_set_nullvalues_for_user',1), 
(29,'2013_11_19_013337_create_asset_logs_table',1), 
(30,'2013_11_19_061409_edit_added_on_asset_logs_table',1), 
(31,'2013_11_19_062250_edit_location_id_asset_logs_table',1), 
(32,'2013_11_20_055822_add_soft_delete_on_assets',1), 
(33,'2013_11_20_121404_add_soft_delete_on_locations',1), 
(34,'2013_11_20_123137_add_soft_delete_on_manufacturers',1), 
(35,'2013_11_20_123725_add_soft_delete_on_categories',1), 
(36,'2013_11_20_130248_create_status_labels',1), 
(37,'2013_11_20_130830_add_status_id_on_assets_table',1), 
(38,'2013_11_20_131544_add_status_type_on_status_labels',1), 
(39,'2013_11_20_134103_add_archived_to_assets',1), 
(40,'2013_11_21_002321_add_uploads_table',1), 
(41,'2013_11_21_024531_remove_deployable_boolean_from_status_labels',1), 
(42,'2013_11_22_075308_add_option_label_to_settings_table',1), 
(43,'2013_11_22_213400_edits_to_settings_table',1), 
(44,'2013_11_25_013244_create_licenses_table',1), 
(45,'2013_11_25_031458_create_license_seats_table',1), 
(46,'2013_11_25_032022_add_type_to_actionlog_table',1), 
(47,'2013_11_25_033008_delete_bad_licenses_table',1), 
(48,'2013_11_25_033131_create_new_licenses_table',1), 
(49,'2013_11_25_033534_add_licensed_to_licenses_table',1), 
(50,'2013_11_25_101308_add_warrantee_to_assets_table',1), 
(51,'2013_11_25_104343_alter_warranty_column_on_assets',1), 
(52,'2013_11_25_150450_drop_parent_from_categories',1), 
(53,'2013_11_25_151920_add_depreciate_to_assets',1), 
(54,'2013_11_25_152903_add_depreciate_to_licenses_table',1), 
(55,'2013_11_26_211820_drop_license_from_assets_table',1), 
(56,'2013_11_27_062510_add_note_to_asset_logs_table',1), 
(57,'2013_12_01_113426_add_filename_to_asset_log',1), 
(58,'2013_12_06_094618_add_nullable_to_licenses_table',1), 
(59,'2013_12_10_084038_add_eol_on_models_table',1), 
(60,'2013_12_12_055218_add_manager_to_users_table',1), 
(61,'2014_01_28_031200_add_qr_code_to_settings_table',1), 
(62,'2014_02_13_183016_add_qr_text_to_settings_table',1), 
(63,'2014_05_24_093839_alter_default_license_depreciation_id',1), 
(64,'2014_05_27_231658_alter_default_values_licenses',1), 
(65,'2014_06_19_191508_add_asset_name_to_settings',1), 
(66,'2014_06_20_004847_make_asset_log_checkedout_to_nullable',1), 
(67,'2014_06_20_005050_make_asset_log_purchasedate_to_nullable',1), 
(68,'2014_06_24_003011_add_suppliers',1), 
(69,'2014_06_24_010742_add_supplier_id_to_asset',1), 
(70,'2014_06_24_012839_add_zip_to_supplier',1), 
(71,'2014_06_24_033908_add_url_to_supplier',1), 
(72,'2014_07_08_054116_add_employee_id_to_users',1), 
(73,'2014_07_09_134316_add_requestable_to_assets',1), 
(74,'2014_07_17_085822_add_asset_to_software',1), 
(75,'2014_07_17_161625_make_asset_id_in_logs_nullable',1), 
(76,'2014_08_12_053504_alpha_0_4_2_release',1), 
(77,'2014_08_17_083523_make_location_id_nullable',1), 
(78,'2014_10_16_200626_add_rtd_location_to_assets',1), 
(79,'2014_10_24_000417_alter_supplier_state_to_32',1), 
(80,'2014_10_24_015641_add_display_checkout_date',1), 
(81,'2014_10_28_222654_add_avatar_field_to_users_table',1), 
(82,'2014_10_29_045924_add_image_field_to_models_table',1), 
(83,'2014_11_01_214955_add_eol_display_to_settings',1), 
(84,'2014_11_04_231416_update_group_field_for_reporting',1), 
(85,'2014_11_05_212408_add_fields_to_licenses',1), 
(86,'2014_11_07_021042_add_image_to_supplier',1), 
(87,'2014_11_20_203007_add_username_to_user',1), 
(88,'2014_11_20_223947_add_auto_to_settings',1), 
(89,'2014_11_20_224421_add_prefix_to_settings',1), 
(90,'2014_11_21_104401_change_licence_type',1), 
(91,'2014_12_09_082500_add_fields_maintained_term_to_licenses',1), 
(92,'2015_02_04_155757_increase_user_field_lengths',1), 
(93,'2015_02_07_013537_add_soft_deleted_to_log',1), 
(94,'2015_02_10_040958_fix_bad_assigned_to_ids',1), 
(95,'2015_02_10_053310_migrate_data_to_new_statuses',1), 
(96,'2015_02_11_044104_migrate_make_license_assigned_null',1), 
(97,'2015_02_11_104406_migrate_create_requests_table',1), 
(98,'2015_02_12_001312_add_mac_address_to_asset',1), 
(99,'2015_02_12_024100_change_license_notes_type',1), 
(100,'2015_02_17_231020_add_localonly_to_settings',1), 
(101,'2015_02_19_222322_add_logo_and_colors_to_settings',1), 
(102,'2015_02_24_072043_add_alerts_to_settings',1), 
(103,'2015_02_25_022931_add_eula_fields',1), 
(104,'2015_02_25_204513_add_accessories_table',1), 
(105,'2015_02_26_091228_add_accessories_user_table',1), 
(106,'2015_02_26_115128_add_deleted_at_models',1), 
(107,'2015_02_26_233005_add_category_type',1), 
(108,'2015_03_01_231912_update_accepted_at_to_acceptance_id',1), 
(109,'2015_03_05_011929_add_qr_type_to_settings',1), 
(110,'2015_03_18_055327_add_note_to_user',1), 
(111,'2015_04_29_234704_add_slack_to_settings',1), 
(112,'2015_05_04_085151_add_parent_id_to_locations_table',1), 
(113,'2015_05_22_124421_add_reassignable_to_licenses',1), 
(114,'2015_06_10_003314_fix_default_for_user_notes',1), 
(115,'2015_06_10_003554_create_consumables',1), 
(116,'2015_06_15_183253_move_email_to_username',1), 
(117,'2015_06_23_070346_make_email_nullable',1), 
(118,'2015_06_26_213716_create_asset_maintenances_table',1), 
(119,'2015_07_04_212443_create_custom_fields_table',1), 
(120,'2015_07_09_014359_add_currency_to_settings_and_locations',1), 
(121,'2015_07_21_122022_add_expected_checkin_date_to_asset_logs',1), 
(122,'2015_07_24_093845_add_checkin_email_to_category_table',1), 
(123,'2015_07_25_055415_remove_email_unique_constraint',1), 
(124,'2015_07_29_230054_add_thread_id_to_asset_logs_table',1), 
(125,'2015_07_31_015430_add_accepted_to_assets',1), 
(126,'2015_09_09_195301_add_custom_css_to_settings',1), 
(127,'2015_09_21_235926_create_custom_field_custom_fieldset',1), 
(128,'2015_09_22_000104_create_custom_fieldsets',1), 
(129,'2015_09_22_003321_add_fieldset_id_to_assets',1), 
(130,'2015_09_22_003413_migrate_mac_address',1), 
(131,'2015_09_28_003314_fix_default_purchase_order',1), 
(132,'2015_10_01_024551_add_accessory_consumable_price_info',1), 
(133,'2015_10_12_192706_add_brand_to_settings',1), 
(134,'2015_10_22_003314_fix_defaults_accessories',1), 
(135,'2015_10_23_182625_add_checkout_time_and_expected_checkout_date_to_assets',1), 
(136,'2015_11_05_061015_create_companies_table',1), 
(137,'2015_11_05_061115_add_company_id_to_consumables_table',1), 
(138,'2015_11_05_183749_image',1), 
(139,'2015_11_06_092038_add_company_id_to_accessories_table',1), 
(140,'2015_11_06_100045_add_company_id_to_users_table',1), 
(141,'2015_11_06_134742_add_company_id_to_licenses_table',1), 
(142,'2015_11_08_035832_add_company_id_to_assets_table',1), 
(143,'2015_11_08_222305_add_ldap_fields_to_settings',1), 
(144,'2015_11_15_151803_add_full_multiple_companies_support_to_settings_table',1), 
(145,'2015_11_26_195528_import_ldap_settings',1), 
(146,'2015_11_30_191504_remove_fk_company_id',1), 
(147,'2015_12_21_193006_add_ldap_server_cert_ignore_to_settings_table',1), 
(148,'2015_12_30_233509_add_timestamp_and_userId_to_custom_fields',1), 
(149,'2015_12_30_233658_add_timestamp_and_userId_to_custom_fieldsets',1), 
(150,'2016_01_28_041048_add_notes_to_models',1), 
(151,'2016_02_19_070119_add_remember_token_to_users_table',1), 
(152,'2016_02_19_073625_create_password_resets_table',1), 
(153,'2016_03_02_193043_add_ldap_flag_to_users',1), 
(154,'2016_03_02_220517_update_ldap_filter_to_longer_field',1), 
(155,'2016_03_08_225351_create_components_table',1), 
(156,'2016_03_09_024038_add_min_stock_to_tables',1), 
(157,'2016_03_10_133849_add_locale_to_users',1), 
(158,'2016_03_10_135519_add_locale_to_settings',1), 
(159,'2016_03_11_185621_add_label_settings_to_settings',1), 
(160,'2016_03_22_125911_fix_custom_fields_regexes',1), 
(161,'2016_04_28_141554_add_show_to_users',1), 
(162,'2016_05_16_164733_add_model_mfg_to_consumable',1), 
(163,'2016_05_19_180351_add_alt_barcode_settings',1), 
(164,'2016_05_19_191146_add_alter_interval',1), 
(165,'2016_05_19_192226_add_inventory_threshold',1), 
(166,'2016_05_20_024859_remove_option_keys_from_settings_table',1), 
(167,'2016_05_20_143758_remove_option_value_from_settings_table',1), 
(168,'2016_06_01_140218_add_email_domain_and_format_to_settings',1), 
(169,'2016_06_22_160725_add_user_id_to_maintenances',1), 
(170,'2016_07_13_150015_add_is_ad_to_settings',1), 
(171,'2016_07_14_153609_add_ad_domain_to_settings',1), 
(172,'2016_07_22_003348_fix_custom_fields_regex_stuff',1), 
(173,'2016_07_22_054850_one_more_mac_addr_fix',1), 
(174,'2016_07_22_143045_add_port_to_ldap_settings',1), 
(175,'2016_07_22_153432_add_tls_to_ldap_settings',1), 
(176,'2016_07_27_211034_add_zerofill_to_settings',1), 
(177,'2016_08_02_124944_add_color_to_statuslabel',1), 
(178,'2016_08_04_134500_add_disallow_ldap_pw_sync_to_settings',1), 
(179,'2016_08_09_002225_add_manufacturer_to_licenses',1), 
(180,'2016_08_12_121613_add_manufacturer_to_accessories_table',1), 
(181,'2016_08_23_143353_add_new_fields_to_custom_fields',1), 
(182,'2016_08_23_145619_add_show_in_nav_to_status_labels',1), 
(183,'2016_08_30_084634_make_purchase_cost_nullable',1), 
(184,'2016_09_01_141051_add_requestable_to_asset_model',1), 
(185,'2016_09_02_001448_create_checkout_requests_table',1), 
(186,'2016_09_04_180400_create_actionlog_table',1), 
(187,'2016_09_04_182149_migrate_asset_log_to_action_log',1), 
(188,'2016_09_19_235935_fix_fieldtype_for_target_type',1), 
(189,'2016_09_23_140722_fix_modelno_in_consumables_to_string',1), 
(190,'2016_09_28_231359_add_company_to_logs',1), 
(191,'2016_10_14_130709_fix_order_number_to_varchar',1), 
(192,'2016_10_16_015024_rename_modelno_to_model_number',1), 
(193,'2016_10_16_015211_rename_consumable_modelno_to_model_number',1), 
(194,'2016_10_16_143235_rename_model_note_to_notes',1), 
(195,'2016_10_16_165052_rename_component_total_qty_to_qty',1), 
(196,'2016_10_19_145520_fix_order_number_in_components_to_string',1), 
(197,'2016_10_27_151715_add_serial_to_components',1), 
(198,'2016_10_27_213251_increase_serial_field_capacity',1), 
(199,'2016_10_29_002724_enable_2fa_fields',1), 
(200,'2016_10_29_082408_add_signature_to_acceptance',1), 
(201,'2016_11_01_030818_fix_forgotten_filename_in_action_logs',1), 
(202,'2016_11_13_020954_rename_component_serial_number_to_serial',1), 
(203,'2016_11_16_172119_increase_purchase_cost_size',1), 
(204,'2016_11_17_161317_longer_state_field_in_location',1), 
(205,'2016_11_17_193706_add_model_number_to_accessories',1), 
(206,'2016_11_24_160405_add_missing_target_type_to_logs_table',1), 
(207,'2016_12_07_173720_increase_size_of_state_in_suppliers',1), 
(208,'2016_12_19_004212_adjust_locale_length_to_10',1), 
(209,'2016_12_19_133936_extend_phone_lengths_in_supplier_and_elsewhere',1), 
(210,'2016_12_27_212631_make_asset_assigned_to_polymorphic',1), 
(211,'2017_01_09_040429_create_locations_ldap_query_field',1), 
(212,'2017_01_14_002418_create_imports_table',1), 
(213,'2017_01_25_063357_fix_utf8_custom_field_column_names',1), 
(214,'2017_03_03_154632_add_time_date_display_to_settings',1), 
(215,'2017_03_10_210807_add_fields_to_manufacturer',1), 
(216,'2017_05_08_195520_increase_size_of_field_values_in_custom_fields',1), 
(217,'2017_05_22_204422_create_departments',1), 
(218,'2017_05_22_233509_add_manager_to_locations_table',1), 
(219,'2017_06_14_122059_add_next_autoincrement_to_settings',1), 
(220,'2017_06_18_151753_add_header_and_first_row_to_importer_table',1), 
(221,'2017_07_07_191533_add_login_text',1), 
(222,'2017_07_25_130710_add_thumbsize_to_settings',1), 
(223,'2017_08_03_160105_set_asset_archived_to_zero_default',1), 
(224,'2017_08_22_180636_add_secure_password_options',1), 
(225,'2017_08_25_074822_add_auditing_tables',1), 
(226,'2017_08_25_101435_add_auditing_to_settings',1), 
(227,'2017_09_18_225619_fix_assigned_type_not_being_nulled',1), 
(228,'2017_10_03_015503_drop_foreign_keys',1), 
(229,'2017_10_10_123504_allow_nullable_depreciation_id_in_models',1), 
(230,'2017_10_17_133709_add_display_url_to_settings',1), 
(231,'2017_10_19_120002_add_custom_forgot_password_url',1), 
(232,'2017_10_19_130406_add_image_and_supplier_to_accessories',1), 
(233,'2017_10_20_234129_add_location_indices_to_assets',1), 
(234,'2017_10_25_202930_add_images_uploads_to_locations_manufacturers_etc',1), 
(235,'2017_10_27_180947_denorm_asset_locations',1), 
(236,'2017_10_27_192423_migrate_denormed_asset_locations',1), 
(237,'2017_10_30_182938_add_address_to_user',1), 
(238,'2017_11_08_025918_add_alert_menu_setting',1), 
(239,'2017_11_08_123942_labels_display_company_name',1), 
(240,'2017_12_12_010457_normalize_asset_last_audit_date',1), 
(241,'2017_12_12_033618_add_actionlog_meta',1), 
(242,'2017_12_26_170856_re_normalize_last_audit',1), 
(243,'2018_01_17_184354_add_archived_in_list_setting',1), 
(244,'2018_01_19_203121_add_dashboard_message_to_settings',1), 
(245,'2018_01_24_062633_add_footer_settings_to_settings',1), 
(246,'2018_01_24_093426_add_modellist_preferenc',1), 
(247,'2018_02_22_160436_add_remote_user_settings',1), 
(248,'2018_03_03_011032_add_theme_to_settings',1), 
(249,'2018_03_06_054937_add_default_flag_on_statuslabels',1), 
(250,'2018_03_23_212048_add_display_in_email_to_custom_fields',1), 
(251,'2018_03_24_030738_add_show_images_in_email_setting',1), 
(252,'2018_03_24_050108_add_cc_alerts',1), 
(253,'2018_03_29_053618_add_canceled_at_and_fulfilled_at_in_requests',1), 
(254,'2018_03_29_070121_add_drop_unique_requests',1), 
(255,'2018_03_29_070511_add_new_index_requestable',1), 
(256,'2018_04_02_150700_labels_display_model_name',1), 
(257,'2018_04_16_133902_create_custom_field_default_values_table',1), 
(258,'2018_05_04_073223_add_category_to_licenses',1), 
(259,'2018_05_04_075235_add_update_license_category',1), 
(260,'2018_05_08_031515_add_gdpr_privacy_footer',1), 
(261,'2018_05_14_215229_add_indexes',1), 
(262,'2018_05_14_223646_add_indexes_to_assets',1), 
(263,'2018_05_14_233638_denorm_counters_on_assets',1), 
(264,'2018_05_16_153409_add_first_counter_totals_to_assets',1), 
(265,'2018_06_21_134622_add_version_footer',1), 
(266,'2018_07_05_215440_add_unique_serial_option_to_settings',1), 
(267,'2018_07_17_005911_create_login_attempts_table',1), 
(268,'2018_07_24_154348_add_logo_to_print_assets',1), 
(269,'2016_06_01_000001_create_oauth_auth_codes_table',2), 
(270,'2016_06_01_000002_create_oauth_access_tokens_table',2), 
(271,'2016_06_01_000003_create_oauth_refresh_tokens_table',2), 
(272,'2016_06_01_000004_create_oauth_clients_table',2), 
(273,'2016_06_01_000005_create_oauth_personal_access_clients_table',2), 
(274,'2019_02_14_154310_change_auto_increment_prefix_to_nullable',3), 
(275,'2019_02_16_143518_auto_increment_back_to_string',3), 
(276,'2019_02_20_234421_make_serial_nullable',3), 
(277,'2019_02_21_224703_make_fields_nullable_for_integrity',3), 
(278,'2019_06_12_184327_rename_groups_table',4), 
(279,'2018_07_28_023826_create_checkout_acceptances_table',5), 
(280,'2018_08_20_204842_add_depreciation_option_to_settings',5), 
(281,'2018_09_10_082212_create_checkout_acceptances_for_unaccepted_assets',5), 
(282,'2018_10_18_191228_add_kits_licenses_table',5), 
(283,'2018_10_19_153910_add_kits_table',5), 
(284,'2018_10_19_154013_add_kits_models_table',5), 
(285,'2018_12_05_211936_add_favicon_to_settings',5), 
(286,'2018_12_05_212119_add_email_logo_to_settings',5), 
(287,'2019_02_07_185953_add_kits_consumables_table',5), 
(288,'2019_02_07_190030_add_kits_accessories_table',5), 
(289,'2019_02_12_182750_add_actiondate_to_actionlog',5), 
(290,'2019_02_17_205048_add_label_logo_to_settings',5), 
(291,'2019_07_23_140906_add_show_assigned_assets_to_settings',5), 
(292,'2019_08_20_084049_add_custom_remote_user_header',5), 
(293,'2019_12_04_223111_passport_upgrade',5), 
(294,'2020_02_04_172100_add_ad_append_domain_settings',5), 
(295,'2020_04_29_222305_add_saml_fields_to_settings',5), 
(296,'2020_10_22_233743_move_accessory_checkout_note_to_join_table',5), 
(297,'2020_10_23_161736_fix_zero_values_for_locations',5);
```

**Comment by shoebwk** [comment]
> Glad you're sorted, @steve1673!
> 
> @shoebwk any updates?

Since I revert back to old version, let me do the migration again.

**Comment by shoebwk** [comment]
> fixed the following:
> 2018_10_19_153910_add_kits_table
> 2018_10_19_154013_add_kits_models_table
> 2019_02_07_185953_add_kits_consumables_table
> 2019_02_07_190030_add_kits_accessories_table
> 
> LDAP is now functional, and all users are visible!
> 
> TY for all of your help. Good luck trying to figure out why others have had this issue with migration, Ping me here if there's any info I can provide that may help.

Hi @steve1673 Could you guide me the command how you inserted records in migration table each time you encountered the error?

**Comment by VanillaNinjaD** [comment]
I had the same issue here and used the same migrations fix suggested by @Snipe going 1 by 1 and updating the migrations table using MySQL workbench. Happily working now

> Migrating: 2018_07_28_023826_create_checkout_acceptances_table
> 
> In Connection.php line 669:
> 
> SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists (SQL: create t
> able `checkout_acceptances` (`id` int unsigned not null auto_increment primary key, `checkoutable_type` varchar(191
> ) not null, `checkoutable_id` bigint unsigned not null, `assigned_to_id` int unsigned not null, `signature_filename ` varchar(191) null, `accepted_at` timestamp null, `declined_at` timestamp null, `created_at` timestamp null, `upda ted_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' eng
> ine = InnoDB)
> 
> In PDOStatement.php line 129:
> 
> SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists
> 
> In PDOStatement.php line 127:
> 
> SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'checkout_acceptances' already exists
> 
> no change to LDAP.

**Comment by snipe** [comment]
@henningkessler If those migrations were not actually run, inserting records directly into the migrations table will cause you no end of heartache, since the schema and the code will be out of sync.

**Comment by henningkessler** [comment]
I added the missing lines and then run
```
php artisan migrate
```
which ended successful but ldap still does not work and I get the exact same errors as steve1673. Is it important to do line by line  and running
```
php artisan migrate
```
after adding each line?

**Comment by VanillaNinjaD** [comment]
> 
> 
> I added the missing lines and then run
> 
> ```
> php artisan migrate
> ```
> 
> which ended successful but ldap still does not work and I get the exact same errors as steve1673. Is it important to do line by line and running
> 
> ```
> php artisan migrate
> ```
> 
> after adding each line?

Yes, if you fill the table completely without running the migrate after each line you are telling the code to skip DB schema changes that it may not have actually performed yet.

**Comment by VanillaNinjaD** [comment]
I'm finding it hard to explain after a long work day but in my instance only some of the migrations were already present but not reflected in the migrations table. In other words, if the migration hasn't been performed on the DB yet, the code will execute successfully then update the migrations table eliminating the need for you to manually update the table.

Only the DB migrations which were performed but failed to be logged in the migrations table cause an error

**Comment by snipe** [comment]
@VanillaNinjaD - nice to see you again :)

And yes, you’re 100% right. While importing the migrations table will let you get through `php artisan migrate` cleanly, it also means you now have code that is expecting a scheme that your database doesn’t have - because it only knows what migrations were run via that table.

**Comment by henningkessler** [comment]
Thanks for the explanation and your patience. I will give this a try as soon as I will be onsite the next time.

**Comment by henningkessler** [comment]
Hi there, happiness over here. I just needed to add
```
INSERT INTO `migrations` VALUES (279,'2018_07_28_023826_create_checkout_acceptances_table',5);
```
and run 
```
php artisan migrate
```
and that did all the rest by itself

Thanks all for your help

Henning
