### ISSUE TITLE
Unable to create Location, Company or Asset Manufacturer

### ISSUE THREAD

**Issue by benny2310** [grokability/snipe-it#8959]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I log into the user interface and navigate to System on the left hand menu I try to then create a new Location, Company or Asset Manufacturer. 

For example when the Location table loads, I then click on Create New and input the relevant information. Then I click Save and I receive the green confirmation window stating that it has been successful but the new entry is not listed in the table.

The data that was entered during the data input process of creating a new Location has been saved to the relevant table in the database.

**To Reproduce**
1. Go to System Menu
2. Click on Location
3. Then click on Create New 
4. Input relevant information
5. Click Save
6. Green success tile stating Location Created Successfuly
7. New location does not show in the Location Table

**Expected behavior**
Once a new Location, Company or Asset Manufacturer has been created it should show in the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/76882646/103465463-985f8600-4d33-11eb-8c76-60c6b40c876c.png)

**Server (please complete the following information):**
 - Snipe-IT Version: - 5.0.11 Build 5695
 - OS: Ubuntu 18.04.5 LTS
 - Web Server: Plesk Obsidian 18.0.31
 - PHP Version: 7.2.34

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser: NA
 - Version: NA

**Error Messages**
- Confirm whether the error is reproducible on the demo: It works as it should in the demo environment.

**Additional context**
- This is a fresh install.
- What method you used to install Snipe-IT: Pulled straight from GitHub using Plesk control panel

Add any other context about the problem here: NA

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by MandoYoda** [comment]
I am having the same issues. Although when I create a company etc I can see it in the database, but the GUI wont show it

**Comment by benny2310** [comment]
Hello,

This is the same problem that I am having.

It creates an entry in the database but the GUI Frontend does not show any records.

Has anyone found a fix for this??

Regards

**Comment by snipe** [comment]
This has been addressed several times in the documentation and in previous Github issues. 

https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated

<img width="861" alt="Screen Shot 2021-01-13 at 2 05 37 PM" src="https://user-images.githubusercontent.com/197404/104516006-7920ee00-55a8-11eb-943e-5cb5ffb104c9.png">




<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/installation-issues#table-listing-pages-load-with-401-unauthorizedunauthenticated">Installation/Upgrading Issues</a></strong></div><div>Common installation/upgrading issues and solutions</div></blockquote>

**Comment by CodyChell** [comment]
@snipe I have just recently found I have this same issue. I've gone through the steps that you posted here, but it is still not working. I found on a previous server running 4.9.3 has the same issue as my fresh install, but restored data (from 4.9.3 instance) to 5.0.13-pre-build, but have the same issue in both places. 

I had services.php and config.php in the 4.9.3 instance. Deleted both files, issue persists. 
I had just the services.php in the 5.0.13 pre instance and the issue persists there as well. 

I check all my extensions and I believe that I have all the requirements. 
4.9.3 instance is on ubuntu 18.04 and php 7.2
5.0.13-pre is on ubuntu 20.04 and php 7.4

I did restore from a vmware snapshot a few weeks ago. It might be an issue? Not sure. Got the idea that might've caused an issue because I'm seeing the same error on the old instance. 
Any ideas for some more troubleshooting steps?

**Comment by snipe** [comment]
Hi there - sorry for the freakishly long time in responding here. This one fell off our radar :( 

Since the time this issue was opened, a ton of changes have been made in Snipe-IT. If you're still seeing this issue in the current version, please open a new issue that includes:

- Version of Snipe-IT you're running
- Specific errors you're seeing in the UI and/or in the browser console and error logs
- Steps to reproduce 
- Whether or not you can reproduce this on the demo (https://demo.snipeitapp.com)

Thanks - and again, sorry for the very late reply. We're doing some cleanup of old issues, so we're rediscovering some older things that didn't get addressed the first time around. 

![BeakerEmbarrased](https://github.com/user-attachments/assets/b0372742-304c-4393-9415-9c70ab0651de)

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
