### ISSUE TITLE
When on /models page, the yellow "Update item" icon redirect to /licences/<id>/edit and not to /models/<id>/edit 

### ISSUE THREAD

**Issue by BenoitFb** [grokability/snipe-it#9284]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When on /models page, the yellow "Update item" icon redirect to /licences/<id>/edit and not to /models/<id>/edit 

**To Reproduce**
1. Go to /models
2. Click on a yellow "Update item" icon
3. See error

**Expected behavior**
1. Go to /models
2. Click on a yellow "Update item" icon
3. Be redirected to /models/<id>/edit

**Comment by troveitech** [comment]
This was fixed in v5.1.3, updated and confirmed on my installation.

**Comment by tippete** [comment]
I still have this issue on v5.1.3 - build 5850, same steps to reproduce the problem
the same issue happens trying to delete the model

Thank you

**Comment by troveitech** [comment]
It's working on v5.1.3 - build 5862 for me.

**Comment by tippete** [comment]
Just upgraded to build 5862 and it's fixed, thank you
